### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by duckcli** [Mastercard/terraform-provider-restapi#1]
Hi,
Is it possible to add an example.tf with some basic use case? 
Thank you

**Comment by rberlind** [comment]
Please also show how to add the binary to a Terraform configuration.

**Comment by rberlind** [comment]
In your example, showing that the correct resource type is "restapi_object" will be helpful.  I had to look at the code to figure that out.

**Comment by DRuggeri** [comment]
Cool - done in 7aba3dc3992b5cc54ceac5cfbe4db839f5df33ac and 8cb7e636e6b42406fab723fbf0b4b95a5a0692fd. Would you mind providing some feedback and closing the issue if it looks good?

**Comment by rberlind** [comment]
Thanks so much.  I will test today or tomorrow.

**Comment by DRuggeri** [comment]
@duckcli, I think this is complete. Feedback is definitely welcome. I'll go ahead and close this, but if you can think of more/better examples feel free to reopen.
