### ISSUE TITLE
Feature request: Support mTSL Authentication in requests

### ISSUE THREAD

**Issue by cageyv** [Mastercard/terraform-provider-restapi#100]
https://en.wikipedia.org/wiki/Mutual_authentication
This will allow making custom requests to the API of Hashicorp products with mTLS auth 
For example for new launched or low supported providers 
[Here](https://github.com/picatz/terraform-google-nomad/tree/master/mtls-terminating-proxy) and [Here](https://github.com/picatz/terraform-google-nomad/blob/master/ssh-mtls-terminating-proxy.go) can find some mtls-terminating-proxy on Golang maybe it will help.

**Comment by DRuggeri** [comment]
Hi, @cageyv , this sounds like a pretty reasonable thing to implement. Do I understand the request to just be supporting standard mTLS via a cert/key? That is, no additional authentication is needed?

**Comment by cageyv** [comment]
@DRuggeri Yes, you're right. Cert/key. And Root CA as is optional parameter. Private CAs are often used for this task.
It works well for applications like Hashicorp Consul or Hashikorp Nomad. They both use mTLS.

**Comment by DRuggeri** [comment]
All set - this was added in `v1.15.0`

Please give it a test and LMK if it's not working as expected.
