### ISSUE TITLE
Getting 401 even though credentials are provided

### ISSUE THREAD

**Issue by nadworny** [Mastercard/terraform-provider-restapi#101]
I'm trying to POST a request using basic auth with the following:

```
terraform {
  required_providers {
    restapi = {
      source = "fmontezuma/restapi"
      version = "1.14.1"
    }
  }
}

provider "restapi" {
  uri = "http://test.com"
  headers = {
    "Authorization": "Basic abc"
  }
  debug = true
  write_returns_object = true
}

resource "restapi_object" "mapping" {
  path = "/elastic/_mapping/"
  data = file("${path.module}/mapping.json")
}
```

Unfortunately I'm getting the following error:
```
Error: Unexpected response code '401': {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/elastic/_mapping/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","
ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/elastic/_mapping/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey"
,"Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}
```
Any idea what I might be doing wrong?

I've also tried with the following but getting the same error:
```
provider "restapi" {
  uri = "http://test.com"
  username = "test"
  password = "test"
  debug = true
  write_returns_object = true
}
```

**Comment by DRuggeri** [comment]
Hi, @nadworny . That sounds very strange. I'm afraid nothing really comes to mind. It looks like the API is elasticsearch from the context and that API does use BASIC.
Have you tried enabling the debug parameters to examine the POST as it is sent? There may be a breadcrumb trail in there that is useful. You could try comparing that output with something that works in cURL or something similar.

**Comment by nadworny** [comment]
After enabling debugging I can see that both of the headers are set properly so I'm really not sure what's wrong:
```
2020-11-02T15:56:53.864+0100 [DEBUG] plugin.terraform-provider-restapi_v1.14.1.exe: 2020/11/02 15:56:53 api_client.go:   Content-Type: application/json
2020-11-02T15:56:53.864+0100 [DEBUG] plugin.terraform-provider-restapi_v1.14.1.exe: 2020/11/02 15:56:53 api_client.go:   Authorization: Basic xxx
```

**Comment by DRuggeri** [comment]
Thanks, @nadworny. I'm curious if that same `Authorization` header from the DEBUG output works with something like cURL?

Otherwise, I'm afraid I can't suggest other venues for research. It does seem the header is being sent appropriately, so perhaps the API expects something else?

**Comment by nadworny** [comment]
Hey, yeah I copy pasted the header from this working curl so not sure why it's not working:
```
curl --location --request POST 'http://xxx.elastic.com/_template/template_xxx' \
--header 'Authorization: Basic xxx' \
--header 'Content-Type: application/json' \
```

**Comment by nadworny** [comment]
Ok I think the problem is that on http I'm getting redirect to https and then the basic auth header won't be propagated? Would that be a possible root cause?

**Comment by DRuggeri** [comment]
Hey, @nadworny - that's a pretty reasonable theory. Are you able to confirm that behavior with the debug output? If you're sending credentials to an http endpoint, but getting redirected to an https endpoint... it'd be totally up to the go HTTP client library as to whether it would propagate the credentials. I've seen plenty of libraries choose not to POST on redirects, for example.

Also, can you say more about "pem certificate" being added? Do you mean something similar to #100 ?

**Comment by nadworny** [comment]
Hey, I'm talking about using self signed certificates so I think it's something different to mtls, for example like the curl command: https://stackoverflow.com/questions/27611193/use-self-signed-certificate-with-curl

**Comment by DRuggeri** [comment]
Yeah, that's actually what is being discussed in that thread. On one hand, [using client certs](https://stackoverflow.com/a/27611319) is discussed... which is what just got incorporated in `v1.15.0`. But, on the other hand, the user is having issues with untrusted certificates.

What you are describing indicates to me that you're not dealing with an issue at the TLS layer - but rather at the HTTP layer. If the TLS portion was failing, you'd be unable to make an HTTP request and receive the 401 response.

**Comment by DRuggeri** [comment]
It's been a while since this issue has had any activity so I'm going to close it for now. Please feel free to reply if you have more info to share.
