### ISSUE TITLE
Support query_string in resource provider 

### ISSUE THREAD

**Issue by abelal83** [Mastercard/terraform-provider-restapi#103]
I don't know if this is normal but Microsoft Azure seems to think so. 

For all http methods it's expected to include a query string for api version to use. 

Here's an example with PUT
`
PUT /subscriptions/.../resourcegroups/ExampleResourceGroup?api-version=2016-02-01  HTTP/1.1
Authorization: Bearer <bearer-token>
Content-Length: 29
Content-Type: application/json
Host: management.azure.com

{
  "location": "West US"
}
`
Now I don't know if this is normal but having this supported in rest provider will allow me to manage resources not supported by terraforms azurerm provider.

**Comment by DRuggeri** [comment]
I agree - this is something that should easily be supported. I'm curious - it may "just work" if you tweak/adjust the `create_path`, `read_path`, `update_path`, and `delete_path`.

In any event, I agree it should be in the provider. I'll work this into the provider as time allows - patches are of course welcome in the meantime!

**Comment by sponte** [comment]
Hey @abelal83, out of interest, how do you authenticate to AzureRM from restapi provider? Did you extract the token from ~/.azure?

**Comment by abelal83** [comment]
Hi @sponte unfortunately I've not had time to work on this yet but my thinking was to use to use az cli and get its token. Once I get a chance to work on it will happily share here!

**Comment by sponte** [comment]
Thanks for getting back to me @abelal83, in the meantime I have come up with a simple Powershell for it:

```powershell
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string] $TenantId,

  [Parameter(Mandatory = $true)]
  [string] $ClientId,

  [Parameter(Mandatory = $true)]
  [SecureString] $ClientSecret
)

$secret = $ClientSecret | ConvertFrom-SecureString -AsPlainText

$request = @{
  grant_type    = "client_credentials"
  client_id     = $ClientId
  client_secret = $secret
  resource      = "https://management.azure.com/"
}

$response = Invoke-RestMethod "https://login.microsoftonline.com/${TenantId}/oauth2/token?" `
  -Method POST `
  -Form $request

$response
```

**Comment by DRuggeri** [comment]
Just a heads up for those watching this one: @NamrathaG  added a PR #112 to support this! I'll close this issue once we have that all squared away.

**Comment by DRuggeri** [comment]
The PR has been merged. Thanks, @NamrathaG and @sirlatrom!
