### ISSUE TITLE
Some issues with datasource

### ISSUE THREAD

**Issue by rberlind** [Mastercard/terraform-provider-restapi#11]
I've noticed a significant issue with the datasource: the GET done by read_object near the end is being done against the same path as the first GET done on line 83.  That means it returns all the objects returned by the first GET and stores data for all the objects in the object identified through the datasource search attributes.  I recommend adding a line with `obj.get_path = path + "/{id}"` before line 142. The second GET will then use the ID returned by the search logic of the datasource code.

Additionally, it seems to me that the call to `d.SetId(obj.id)` on line 139 is not needed since the same call is made on line 146 which is where it is really needed.  Even if you were going to keep the call on line 139, it seems to me that it should be done after the call to `obj.id = id` that is currently on line 140.

Additionally, the call to `d.Id()` in line 65 does not make sense to me. I don't think the d object will have any ID at that point in the execution of the code, at least not when the datasource is first added to the Terraform configuration. I suggest setting the id being passed to NewAPIObject to "0".  This will avoid having to set create_returns_object to true in the provider configuration in order to use the datasource which is currently the case since if NewAPIObject sees a blank id (""), it checks to make sure that at least one of create_returns_object or write_returns_object is set to true.  But the user should not be forced to set these to true if they don't need them set to true for their resources.

I've actually made these and some other modifications to the datasource code, but have avoided pushing my changes to Github since I would prefer those be handled on a separate branch in my fork and have not had time to do set that up yet.  But I do hope to submit a pull request some time this week.

**Comment by rberlind** [comment]
See https://github.com/Mastercard/terraform-provider-restapi/pull/12

**Comment by DRuggeri** [comment]
Excellent! Huge thank you for your contribution. I've added a few comments in the PR via the code review tool. Let's keep the conversation rolling in the PR and once the few things are addressed, I'll merge them in and roll a release.

**Comment by rberlind** [comment]
Thanks.  I will review today or tomorrow (I hope).

**Comment by DRuggeri** [comment]
I did a refactor of the datasource to add some features, safety and make it a bit cleaner as part of #14. I incorporated several ideas from this PR, too. Please give it a look and let me know if this issue and #12 is still needed.

**Comment by rberlind** [comment]
I've been busy on other projects and am sorry for not following up on this.  I will check it out this weekend.

**Comment by rberlind** [comment]
Hi @DRuggeri :  I looked at your new version of datasource_api_object.go and think it looks fine as far as the refactoring and improved error checking is concerned.  I see that you are now calling GetObjectAtKey() in common.go which also looks fine.

What I would still like to see is the ability to parse search_key the way I do in https://github.com/rberlind/terraform-provider-restapi/blob/datasource-enhancements/restapi/datasource_api_object.go.  I think we could add that by doing a second call to GetObjectAtKey() inside the data_array loop starting after line 119.  I think that call would look like this including line 119:

```
    hash := item.(map[string]interface{})
    search_hash, err = GetObjectAtKey(hash, search_key, debug)
    if err != nil {
      return fmt.Errorf("datasource_api_object.go: Error parsing seach_key: %s", err)
    }
    if _, ok = search_hash.(map[string]interface{}); !ok {
      return fmt.Errorf("datasource_api_object.go: The results of parsing '%s' did not return a hash.", search_key)
    }
    
     /* We found our record */
    if search_hash[search_key] == search_value {
```

I have not yet tried to implement this.  But what do you think?

**Comment by rberlind** [comment]
Well, it was a bit more complicated than that since I had to break up a multi-part search_key into the last part and the rest before it.  I tested that the following worked:

```
  /* Loop through all of the results seeking the specific record */
  for _, item := range data_array {
    hash := item.(map[string]interface{})

    /* Parse search_key in case it has multiple levels*/
    var tmp interface{}
    var search_hash map[string]interface{}
    var reduced_search_key string
    search_parts := strings.Split(search_key, "/")
    final_search_part := search_parts[len(search_parts) - 1]
    if debug { log.Printf("datasource_api_object.go: final_search_part: '%s'", final_search_part) }
    if len(search_parts) > 1 {
      /* strip off last search_part and recombine */
      search_parts = search_parts[:len(search_parts) - 1]
      reduced_search_key = strings.Join(search_parts, "/")
      if debug { log.Printf("datasource_api_object.go: reduced_search_key: '%s'", reduced_search_key) }
      tmp, err = GetObjectAtKey(hash, reduced_search_key, debug)
      if err != nil {
        return fmt.Errorf("datasource_api_object.go: Error parsing seach_key: %s", err)
      }
      if search_hash, ok = tmp.(map[string]interface{}); !ok {
        return fmt.Errorf("datasource_api_object.go: The results of parsing '%s' did not return a hash.", reduced_search_key)
      }
    } else {
      search_hash = hash
    }

    /* We found our record */
    if search_hash[final_search_part] == search_value {
      id = fmt.Sprintf("%v", search_hash[id_attribute])
      if debug { log.Printf("datasource_api_object.go: Found ID %s", id) }

      /* But there is no id attribute??? */
      if "" == id {
        return(errors.New(fmt.Sprintf("The object for '%s'='%s' did not have the id attribute '%s'", search_key, search_value, id_attribute)))
      }
      break
    }
  }
```
This was with the following datasource:
```
data "restapi_object" "tfe_workspace" {
  path = "/organizations/Cloud-Operations/workspaces"
  id_attribute = "name"
  results_key = "data"
  search_key = "attributes/name"
  search_value = "gcp-compute-instance"
  debug = true
}
```
I will do new PR for this

**Comment by rberlind** [comment]
Submitted https://github.com/Mastercard/terraform-provider-restapi/pull/15

**Comment by DRuggeri** [comment]
Cool - please see the feedback in #15 and let me know if this issue is good to be closed.

**Comment by rberlind** [comment]
Yes, I tested release 1.5.1 with a data source for which search_key was "attributes/name" and it worked.  Closing this issue.
