### ISSUE TITLE
pass headers in a restapi_object

### ISSUE THREAD

**Issue by alexinthesky** [Mastercard/terraform-provider-restapi#113]
Hi,
I'm looking for a way to pass additionnal headers to a restapi_object , on top of the ones set in the provider section.

Is this possible?

**Comment by DRuggeri** [comment]
Hi there, @alexinthesky. Not at present, no.

Can you help me understand the use case for passing per-resource headers versus what the provider has configured? If it's a common enough use case, it'd be reasonable to add to the provider.

**Comment by DRuggeri** [comment]
It's been a while since this issue has had any activity so I'm going to close it for now. Please feel free to reply if you have more info to share.

**Comment by Satak** [comment]
Hey @DRuggeri, we have use case where we get new token after each http request and we would have to update the header in each `restapi_object` call.

Basic workflow:
1st request to create new record (new token is in http output)
2nd request to new API endpoint with 1st request output token in header (yet new token is created and it is in output)
3rd request to new API endpoint where we need to use the token from 2nd request.

How would you construct such a multi-step API request? If we could pass header object to `restapi_object` this would be then trivial.

**Comment by Satak** [comment]
Can we re-open this issue?

**Comment by philippeckelintive** [comment]
@Satak I don't know if you're still facing this issue, but for who ever is interested:

For using, simply using a secondary provider using [alias](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations) configured with the additional headers works:

```hcl
provider "restapi" {
  uri = "https://api.example.com"
  headers = {
    "Authorization" = var.api_token
    "Content-Type"  = "application/json"
  }
}

provider "restapi" {
  alias = "new_token"
  uri   = "https://api.example.com"

  headers = {
    "Authorization" = restapi_object.new_mgmt_token.api_data.token
    "Content-Type"  = "application/json"
  }
}
```
