### ISSUE TITLE
Terraform second time apply is failing with conflict issue

### ISSUE THREAD

**Issue by macysre** [Mastercard/terraform-provider-restapi#116]
Hi Guys, Thank you for awesome restapi provider. 

I have observed, terraform apply working fine for POST call first time, when we run terraform apply second time without change, its throwing http response code 422, id/name is unique. 

And, terraform destroy is not working as expected, its deleting entries from state file but not actual resources which was created through this module.

**Comment by DRuggeri** [comment]
Hi there, @macysre. It's good that you have the first apply working - that's half the battle!

The `422` error is quite strange. That's defined as an unprocessable entity error - which would be very API-specific in terms of what it means. Have you gone beyond setting the basics like `path` and `data`?

It would probably be a good idea to take a look at the debug log output and see what request is being made that results in the `422`. From there, hopefully the request being made can be matched up to the API docs to see if it's a valid request for that API.

**Comment by DRuggeri** [comment]
It's been a while since this issue has had any activity so I'm going to close it for now. Please feel free to reply if you have more info to share.
