### ISSUE TITLE
State is corrupted after a run with invalid data

### ISSUE THREAD

**Issue by m-v-k** [Mastercard/terraform-provider-restapi#117]
When the data input is not valid, for whatever reason, after apply is run it gives an error obviously.
However the data is updated in the state.
From now on the state is corrupted because even when coorecting the data input error, it can never create a succesfull plan again.

reproduce:
- set up a working api_object and run it
- change the data input (json) to be invalid json.
- run again
- revert the data input to valid json
- run again
- ERROR

**Comment by DRuggeri** [comment]
Thanks for the report @m-v-k. I've been focusing on a few other things in the repo at the moment, but haven't forgotten the issue. I'll be happy to take a look as soon as I can

**Comment by DRuggeri** [comment]
Thanks again, @m-v-k  - this is fixed in ec5248a628807e7332262b2d345a8c5c73885685 (fixes cases where the stat is corrupt and we can continue) and I also added a followup in b752a5fffe589c3d21b764e8ce75a609892e3467 for Terraform to reject invalid JSON input before the provider is even invoked.
