### ISSUE TITLE
DataDog API

### ISSUE THREAD

**Issue by wb529kq** [Mastercard/terraform-provider-restapi#126]
anyone using this with datadog and have a working config...

Getting ...
Error: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!

**Comment by wb529kq** [comment]
id_attribute = "org"
  object_id = "org"

**Comment by wb529kq** [comment]
The API is a little broken they create id is org but the read id is a unique public id returned after the create process.
I couldnt immediately see a way to have a create id and a read id.
The path is the same.

**Comment by DRuggeri** [comment]
That sounds pretty odd indeed - but I may not follow completely. Can you share a config example and then create/read response from the server? It's possible that this provider can't help, but seeing the "guts" of request/response could help confirm.

**Comment by wb529kq** [comment]
thanks for the response I gave up with that part of the datadog API and went another direction while they fix the API to be a little more ... "sane"
