### ISSUE TITLE
release filename invalid for windows platform, extension is missing

### ISSUE THREAD

**Issue by dmachard** [Mastercard/terraform-provider-restapi#130]
Hi,

The name of plugin for windows platform is invalid for terraform,  **exe** extension is missing

https://github.com/Mastercard/terraform-provider-restapi/blob/39efa7c7e5faeb9a2b14580a16f9f654b6f2da76/scripts/do_release.sh#L67

the following error occured with terraform during apply: `Error: Could not load plugin`

Denis

**Comment by DRuggeri** [comment]
Thanks, @dmachard - I've gone ahead and fixed this in 5b77e41bd96e4838b2a8468f4e465e3911918e34 and will release it soon
