### ISSUE TITLE
How to use the auth token 

### ISSUE THREAD

**Issue by endejoli** [Mastercard/terraform-provider-restapi#134]
I am trying to generate a azure token using this provider, below is my code

```
provider "restapi" {
  alias                = "restapi_headers"
  uri                  = "https://login.microsoftonline.com/<subid>/oauth2/token"
  debug                = true
  write_returns_object = true
  oauth_client_credentials {
      oauth_client_id = "#######"
      oauth_client_secret = "#####"
      oauth_token_endpoint = "https://management.azure.com"
      oauth_scopes = ["openid"]
  }

}
```
My question is, once I generate the  OAuth token, how do I use that in subsequent resources? I would like to make an in-house api call by passing the bearer token I generated from the above call

**Comment by endejoli** [comment]
Can anyone help me with this, please? I would like to avoid using local-exec and curl

**Comment by DRuggeri** [comment]
Hi, @endejoli  - thanks for checking in. I'm not sure I understand the question. The configuration you have *should* work... the client will [attempt to obtain a token](https://github.com/Mastercard/terraform-provider-restapi/blob/d37a88727a07b7552a862228c41455a79949a19d/restapi/api_client.go#L233-L240) just before making a call to manage the API object. The snippet you provide is correct for establishing the provider, but the `api_object` resource is missing - so the provider won't actually *do* anything per se...

Tagging @SvenHamers (who helped by writing this base implementation) for awareness.

Is this actually failing when attempting to create/manage an object? If so, do you have some additional logging information available to triage? Feel free to reopen the issue if that's the case!
