### ISSUE TITLE
Lists and Embedded Resource Support?

### ISSUE THREAD

**Issue by acalbazana** [Mastercard/terraform-provider-restapi#141]
Hello,

I have a couple of questions about a use case for the rest provider.  I have an endpoint that exposes a resource that has a sub-resource attached.  The sub-resource is simply a list of key-value pairs and does not have its own identity.  The lifecycle of the sub-resource is entirely dependent on its parent (which does have an identity).  So, two questions:

1. Does the provider support a list semantic as valid JSON?  Or, does it require ALL resources to be map-based with an identity?
2. Is there a way to support embedded resources if their lifecycle is attached to a parent?

Quick Example:

Parent Resource:

endpoint = https://my.api.com/samples/parent/1000
representation = {"id":1000, "name":"foo"}

Embedded Resource:

endpoint = https://my.api.com/samples/parent/1000/embedded-sub-resource
representation = [{"key1":"value1"}, {"key2":"value2"}]

A PUT to the embedded resource's endpoint adds a new list of key/value pairs tied to the parent.  A DELETE on the parent, should destroy both.

Thanks!

Alejandro

**Comment by DRuggeri** [comment]
Hey there, @acalbazana - thanks for checking in

The way you've described and captured the summary is absolutely spot on - this provider is designed to support full lifecycle management of discrete objects. Working with sub-objects *may* be possible, but is not a target for this provider unless those sub-objects have their own identity.

An expected example that should work fine:
```
resource "restapi_object" "parent" {
  path = "/parent"
  data = "{ \"name\": \"foo\" }"
}

resource "restapi_object" "child_of_parent" {
  path = "/parent/${restapi_object.parent.id}/"
  depends_on = [ restapi_object.parent ]
  data = "{ \"child\": \"foo\" }"
}
```
... which expects that both the creation of the parent and child returns an ID.

**Comment by DRuggeri** [comment]
I forgot to mention: if you think this *should* work, though, feel free to reopen the issue. It would also be great to create a working example if you find a recipe that helps out!
