### ISSUE TITLE
Delete API not triggered on destroy

### ISSUE THREAD

**Issue by emmaroberts-nbs** [Mastercard/terraform-provider-restapi#143]
Currently has an API that only supports create and delete. When running terraform destroy, terraform is not picking that the  restapi_object needs to be destroyed so the state file is been updated to remove the state of the restapi_object, but the invocation of the delete endpoint is not hit.

I'm currently using the latest publish version on terrafrom registry from fmontezuma.

Terraform code looks like this:
#### _**providers.tf**_ 
```hcl
terraform {
  required_providers {
   external = {
      source = "hashicorp/external"
    }
    restapi = {
      source = "fmontezuma/restapi"
    }
  }
  required_version = ">= 0.15"
}

provider "restapi" {
  uri = "http:"
  headers = {
    "Accept"       = "application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json"
    "Content-Type" = "application/json"

  }
  write_returns_object  = true
  create_returns_object = true
}

```

#### _**main.tf**_ 
```hcl
locals {
 folder_name = "/tmp/files"

}
data "local_file" "main_schema" {
  filename = "${local.folder_name}/${var.schema_file}"
}

data "external" "main_schema" {
  program = ["bash", "${path.module}/files/addRefsToPayload.sh"]
  query = {
    current_payload = jsonencode({ "schema" : data.local_file.main_schema.content, "schemaType" : "PROTOBUF", "references" : [] })
    file_name       = "${local.folder_name}/${var.schema_file}"
  }
}
resource "restapi_object" "main_schema" {
  for_each      = var.subjects
  path          = "${var.base_schema_subject_url}/${each.key}-value/versions/{id}"
  create_method = "POST"
  update_method = "POST"
  update_path   = "${var.base_schema_subject_url}/${each.key}-value/versions"
  create_path   = "${var.base_schema_subject_url}/${each.key}-value/versions"
  destroy_method = "DELETE"
  data          = data.external.main_schema.result.payload
  id_attribute  = "id"
}
```

```hcl
variable "subjects" {
  type        = set(string)
  description = "Set of subject names that the schema should be assigned to"
  default = ["test"]
}
variable "base_schema_subject_url" {
  type        = string
  description = "URL for the subject. "
 default = "//localhost:8081/subjects"
}

variable "schema_file" {
  type = string
  default = "main_schema.proto"
}
```

Running this will terraform version 0.15.3

When running `terraform destroy`, the result is:
![Screenshot 2021-06-30 at 13 53 52](https://user-images.githubusercontent.com/74302098/123963727-a7558700-d9aa-11eb-858f-9a55ac469cdd.png)

When during a get on the api in question, the created resource from the restapi_object still exists

**Comment by emmaroberts-nbs** [comment]
As part of this issue, if I keep running terraform apply, the restapi_object keeps wanting to be created even 

Steps to replicate:
```bach
terraform apply
# Changes applied successfully
# Make no changes to the terraform 
terraform apply
```

Observed behaviour:
Second run will want to create the same resource as the 1st run. This happens on every terraform apply.

Expected behaviour:
Second run of terraform apply with no changes should come back with No changes

**Comment by emmaroberts-nbs** [comment]
So this issue might be done to dynamically generated payload. 

When I try the following configuration:
```
provider "restapi" {
  uri = "http://${var.schema_registry_domain}"
  headers = {
    "Accept"       = "application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json"
    "Content-Type" = "application/json"

  }
  write_returns_object  = true
  create_returns_object = true
}
resource "restapi_object" "mode" {
  provider = restapi
  path           = "/mode"
  create_method  = "PUT"
  create_path    = "/mode"
  update_path    = "/mode"
  destroy_method = "GET"
  destroy_path   = "/mode"
  read_path      = "/mode"
  data           = jsonencode({ "mode" : "READWRITE" })
  id_attribute   = "mode"
  debug          = true
}
```

terraform apply worked and on the second run it didn't detect any changes
When running `terraform destroy` on this configuration, the api is triggered.

Any suggestions as to why this happening?

**Comment by DRuggeri** [comment]
Hey there, @emmaroberts-nbs - thanks for checking in!

Your summary helps a lot - and there's an explanation indeed! There is [a function](https://github.com/Mastercard/terraform-provider-restapi/blob/298e1d56e4a61f2897f81ce499aaee255424efda/restapi/resource_api_object.go#L285-L304) that Terraform itself will use to determine if an object exists. In your case, because the API does not offer a read method (usually GET), this HTTP request will always result in an error. This error is coaxed to a "nope, that does not exist" response to Terraform.

Therefore, when Terraform is calculating the plan to delete, it is detecting that this resource does not exist and does not plan to invoke the [delete function](https://github.com/Mastercard/terraform-provider-restapi/blob/298e1d56e4a61f2897f81ce499aaee255424efda/restapi/resource_api_object.go#L285).

I'm afraid that, given the limitations of the API you are working with, there is no clean way to avoid this situation.

Feel free to reopen the issue with more details if something might allow this to be done!

**Comment by shawnchapla-8451** [comment]
I've also run into a similar issue working with an API which doesn't have a true "GET /other-things/{id}/things/{id}" URL for the pre-destroy read action. It has a general "GET /other-things/{id}/things" API which returns all resources of this type, including their IDs.

I've looked at whether I could use the read_path and read_search parameters of this provider, which I think would be something along the lines of:

```
resource "restapi_object" "thing" {
  for_each  = local.list-of-other-things
...
  path = "/other-things/${each.value}/things"
  read_path = "/other-things/${each.value}/things"
  read_search = {
    "search_key": "id",
    "search_value": "<returned ID of this resource>"
  }
```

However, I essentially need to be able to reference the current object (i.e., "self") to get the ID that was returned when it was created.  Essentially I want to be able to allow the restapi provider to confirm that a resource exists so it can delete it with destroy.  It doesn't appear Terraform has any notion of "self", so wondering if there's another way this might be achieved with the provider?
