### ISSUE TITLE
Active

### ISSUE THREAD

**Issue by wb529kq** [Mastercard/terraform-provider-restapi#148]
Is there a fork in active development that anyone can recommend ?

**Comment by DRuggeri** [comment]
The provider is mostly complete, so there isn't a lot of development happening. There are lots of suggestions for edge cases... but I'm not sure of anything critically missing that a fork would be needed.

Is there a specific functionality you are seeking?

**Comment by DRuggeri** [comment]
We'll call it good for now... feel free to reopen w/ additional info
