### ISSUE TITLE
Support the PATCH method to update resources

### ISSUE THREAD

**Issue by asnowfix** [Mastercard/terraform-provider-restapi#150]
Was adding support for https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH / https://datatracker.ietf.org/doc/html/rfc5789 ever be considered here? MDN makes it clear that it might not be idempotent, but some API providers do not support PUT.

**Comment by NicoK** [comment]
I was successfully using `PATCH` for `create_method` and `update_method`, so that seems to be working

**Comment by asnowfix** [comment]
@NicoK , do you mean that the providers knows how to generate a PATCH on _multiple_ properties based on resource update where _multiple_ fields are changed? I will have a look: I possibly wrongly assumed that multiple PATCH calls would be required, one per changed property.

**Comment by DRuggeri** [comment]
Ah, yes - what you describe, @asnowfix wouldn't be something this provider is capable of supporting. Today, we don't have a way to know exactly which properties changed, so wouldn't be able to calculate the delta of individual properties to PATCH.

What would happen on a change: the full contents of the `data` element will be sent as body with the `update_method`

**Comment by asnowfix** [comment]
Thanks @DRuggeri : no diff. Would the code supporting the PATCH verb support building a proper "op"-based payload structure as defined in [RFC5789](https://datatracker.ietf.org/doc/html/rfc5789), attempting to set _all_ properties, or would it use the PATCH verb with the PUT payload structure?

**Comment by DRuggeri** [comment]
NP, @asnowfix. The payload would be exactly the same as what is specified in the `data` element. Said another way, it uses the exact same HTTP request as `PUT`... but instead just uses the `PATCH` (or whatever is set in `update_method`) verb.

Reading the RFC shared, it doesn't seem like a standard way of defining what changed in the body has been developed which would mean that this is in API-specific territory to be defined.

**Comment by inviul** [comment]
I want to make PATCH api call using resapi provider, but, neither create_method nor update_method working for me. 

Error: unexpected response code '400': {"$id":"1","innerException":null,"message":"Permissions request cannot be null","typeName":"System.InvalidOperationException, mscorlib","typeKey":"InvalidOperationException","errorCode":0,"eventId":0}
