### ISSUE TITLE
Help wanted: Proper ID_Attribute value

### ISSUE THREAD

**Issue by jku-sr** [Mastercard/terraform-provider-restapi#151]
I'm trying to interact with this Rest API from SMTP2Go to manage User Creations
https://apidoc.smtp2go.com/documentation/?_ga=2.153828474.339532667.1634068936-1665400423.1622123068#/POST%20/users/smtp/add

```
RESPONSE Example
{
  "request_id": "aa253464-0bd0-467a-b24b-6159dcd7be60",
  "data": 
  {
    "results": 
    [
      {
        "username": "smtpuser@example.com",
        "email_password": "Password12345",
        "custom_ratelimit": true,
        "custom_ratelimit_value": 100,
        "custom_ratelimit_period": "1 day",
          "comments": "Comment explaining how amazing this Test person is"
        }
    ]
  }
}
```

I believe the id_attribute I need is the "username" attribute but it is nested a few levels down in the JSON response.

I'm running TF 0.13.2
RestApi v1.14.1

```
provider "restapi" {
  uri                   = https://api.smtp2go.com/v3
  debug                 = true
  write_returns_object  = true
  create_returns_object = true
  headers = {
    content-type = "application/json"
    api_key      = KeyValue123456Test

  }
}

resource "restapi_object" "smtpuser" {
  path         = "/users/smtp/add"
  destroy_path = "/users/smtp/remove"
  read_path    = "/users/smtp/view"
  object_id    = "request_id/data/results/username"
  id_attribute = "request_id/data/results/username"
  data         = "{\"username\": \"smtpuser@example.com\", \"description\": \"I am a test user\"} "
}

```
This results in:

restapi_object.sram_test_mail: Creating...

Error: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!

Even though there's an error, the object is created. I'm thinking it's just not capturing the ID value correctly from the JSON response. am I setting my id_attribute and maybe my object_id correctly?

**Comment by jpmonge86** [comment]
Hello,

If you intend on using `username` , then I believe the right attribute would be this:
`id_attribute = "data/results/0/username"`
