### ISSUE TITLE
support for dynamic block inside resource

### ISSUE THREAD

**Issue by kmkramer** [Mastercard/terraform-provider-restapi#154]
I just wanted to confirm that this is not implemented. I need to generate a dynamic variable to be used in the path during for_each. When I add a block it say it isn't expected.

```
Terraform v0.12.29
+ provider.local v2.1.0
+ provider.restapi v1.14.1
```

TIA

**Comment by kmkramer** [comment]
ok I'm most likely not doing it correctly. I think a basic example would be just to place an example block in the resource and `terraform plan`.

Let me try to work up an example using the example fakeserver.

**Comment by kmkramer** [comment]
I don't believe I can use a dynamic block in the resource definition since the resource only allows a select few argument references and no "blocks" like other providers.

**Comment by DRuggeri** [comment]
Thanks, @kmkramer. Having reviewed the dynamic blocks myself, I agree that the provider doesn't support it. If you can share your use case a bit more on how it would be beneficial, it might be worth considering as a PR - but I'd be concerned about adding "too much" functionality to such a simple provider.

Feel free to add comments or reopen!
