### ISSUE TITLE
does this support only json format of post data ?

### ISSUE THREAD

**Issue by narasimha18sv** [Mastercard/terraform-provider-restapi#157]
I have a rest api call which needs content-type to be x-www-formurlencoded. when I tried with the same format for the data in the restapi_object resource I am getting below error.

Error: data attribute is invalid JSON:invalid character 'g' looking for the beginning of value.

Please let me know if this format is supported? if yes, how to provide the body for the data attribute

**Comment by DRuggeri** [comment]
Hi, @narasimha18sv  - thanks for reaching out. No, I'm afraid the provider supports only JSON POST format and there are no plans to move to form encoding as that would likely lead to breaking our ability to read the responses.
