### ISSUE TITLE
Working with API POST that does not return anything thus no ID is available to the provider

### ISSUE THREAD

**Issue by wb529kq** [Mastercard/terraform-provider-restapi#165]
... is there a way to work around this other than fix the API method ?

╷
│ Error: internal validation failed; object ID is not set, but *may* have been created; this should never happen
│
│   with restapi_object.create_ci,
│   on main.tf line 42, in resource "restapi_object" "create_ci":
│   42: resource "restapi_object" "create_ci" {

**Comment by DRuggeri** [comment]
Hi, @wb529kq - it's unlikely unless you have a way to predict what ID the API will use for the resource. For example, if you POST to `/api/users` something like:
```
{
  "user": "DRuggeri",
  "first": "Daniel",
  "last": "Ruggeri"
}
```

... and the API would just make available the new user at `/api/users/DRuggeri`, then you could set the ID parameter in your resource directly.

I hope that helps - without more details of the API, I'm not sure if there's a way around the constraint.
