### ISSUE TITLE
Make PUT request

### ISSUE THREAD

**Issue by bufnitza** [Mastercard/terraform-provider-restapi#17]
Hello. I know this is not an issue but rather me misunderstanding how the module works, but please bear with me here.

I'm trying to make a PUT request to modify a CloudFlare resource via its API. However, for some reason, I cannot convince the restapi provider to send a PUT request. It always POSTs.

Here is my particular snippet:
```
resource "cloudflare_load_balancer_pool" "ext_api" {
  name  = "api-pool"

  origins {
    name    = "origin-1"
    address = "10.0.0.1"
  }

  origins {
    name    = "origin-2"
    address = "10.0.0.2"
  }

  minimum_origins    = "1"
}

provider "restapi" {
  uri                  = "https://api.cloudflare.com"
  write_returns_object = true
  debug                = true

  headers {
    X-Auth-Email = "${var.cloudflare_api["email"]}"
    X-Auth-Key   = "${var.cloudflare_api["token"]}"
    Content-Type = "application/json"
  }
}

resource "restapi_object" "ext_api_pool" {
  path         = "/client/v4/user/load_balancers/pools"
  object_id = "${cloudflare_load_balancer_pool.ext_api.id}"

  data = <<EOF
{
  "name": "api-pool",
  "minimum_origins": 1,
  "origins": [
    {
      "name": "origin-1",
      "address": "10.0.0.1",
      "enabled": true,
      "weight": "${var.origin1_weight}"
    },
    {
      "name": "origin-2",
      "address": "10.0.0.2",
      "enabled": true,
      "weight": "${var.origin2_weight}"
    }
    ]
  }EOF
}

```

On each run, the result is the following:
```
* restapi_object.ext_api_pool: Unexpected response code '409': {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1003,
      "message": "value not unique"
    }
  ],
  "messages": []
}
```

This is due to restapi POSTing and trying to create the resource again, conflicting with the existing one created by the Cloudflare module. I want it to PUT that request so that the weights are modified.

What am I doing wrong here? I tried:
- putting the ID in the path. No dice, it sends POST as well
- using id_attribute. Still POST
- putting "id" in the "data". Forever POST.

I may be missing something very subtle here, but please help.

Regards,
Claudiu

**Comment by DRuggeri** [comment]
Hey there. The provider uses different methods for various actions. If you desire a PUT, that means an update to a managed config. So, I think you probably want to import the object into your state (as noted in README) first, THEN make your changes.

**Comment by bufnitza** [comment]
Thanks for the quick answer. I understand and while it does make sense, it is not exactly how I planned the usage. I'm looking for an alternative to using a local_exec with curl in order to perform arbitrary REST calls (not caring about state). It seems that my use case isn't appropriate. It would be difficult (if possible at all) to import the state of a resource which is created via a different provider in the same "apply" run.

Thank you for the insight nonetheless. Have a good one!
