### ISSUE TITLE
Rest API terraform script

### ISSUE THREAD

**Issue by navreddy36** [Mastercard/terraform-provider-restapi#18]
Can you provide me sample terraform template for update, create and delete using JSON payload? 
in this provider, I am seeing only for adding.

**Comment by DRuggeri** [comment]
Hi there. I'm afraid this provider isn't used to just update/create/delete an object. The object must be managed by Terraform to deal with update/delete by changing the object. If the object already exists in the target API, you probably just need to import it with this provider so you can manage changes/delete it with terraform.
