### ISSUE TITLE
Set API_DATA_IS_SENSITIVE in Provider configuration

### ISSUE THREAD

**Issue by daniel-butler-irl** [Mastercard/terraform-provider-restapi#183]
I would like to be able to set `API_DATA_IS_SENSITIVE=true` in the provider configuration. This is so I do not need to rely on
end users setting the environment variable.

Are there any technical reasons this cannot be done? 

```hcl
terraform {
  required_providers {
    restapi = {
      source = "Mastercard/restapi"
      version = "1.17.0"
    }
  }
}

provider "restapi" {
   api_data_is_sensitive = true
}
```

**Comment by DRuggeri** [comment]
Hi, @daniel-butler-irl, that may be possible, but I have not experimented with it. The resource definitions in `restapi/resource_api_object.go` require the Sensitive flag to be set. However, maybe during parsing of parameters, this can be changed later? I'd welcome experimentation/PRs on the idea. It may just work?
