### ISSUE TITLE
I can't use GET all HTTP request

### ISSUE THREAD

**Issue by adeniyistephen** [Mastercard/terraform-provider-restapi#185]
I tried to do a `GET` all request for my API provider, but it seems it's not implemented yet, because I have to provide a `search_key` and a `search_value` for my `GET` data module and a `data` for my resource, so it does not allow to get an array of my requests, is there a way to get all or is it a feature that would be implemented in the future?
Maybe if `search_key` and `search_value` or `data` in resources are not required it might work out.

**Comment by DRuggeri** [comment]
@adeniyistephen  - I'm not sure how to help address this without more details such as a configuration or specific error messages.

I see this was opened quite a while ago, so perhaps a non-issue anymore. I'll close this issue, but feel free to reopen with more information.
