### ISSUE TITLE
cannot unmarshal array into Go value of type map[string]interface

### ISSUE THREAD

**Issue by arun-a-nayagam** [Mastercard/terraform-provider-restapi#188]
Hi,
I have an API that responds like this,
/AccountPlans

> [
    {
        "RateLimit": 150,
        "Description": "Silver",
        "QuotaInterval": "DAY",
        "Uuid": "1762621d-1fa7-406b-a622-e45ba67e5505",
        "Quota": 100000,
        "DefaultPlan": false,
        "OrganizationUsage": "9",
        "ApiIds": {
            "results": []
        },
        "__metadata": {
            "uri": "http://portal.api-dev.test.com:8080/portal-data/Portal.svc/AccountPlans('1762621d-1fa7-406b-a622-e45ba67e5505')"
        },
        "Name": "Silver"
    },
    {
        "RateLimit": 1000,
        "Description": null,
        "QuotaInterval": "MONTH",
        "Uuid": "5883272d-8959-4626-85b2-f1e134dc297b",
        "Quota": 30000,
        "DefaultPlan": false,
        "OrganizationUsage": "0",
        "ApiIds": {
            "results": []
        },
        "__metadata": {
            "uri": "http://portal.api-dev.test.com:8080/portal-data/Portal.svc/AccountPlans('5883272d-8959-4626-85b2-f1e134dc297b')"
        },
        "Name": "test"
    }
]

And I am trying to read one of those resources with a datasource like this,

> data "restapi_object" "acp_silver" {
  provider = restapi.restapi_oauth
  path = "/AccountPlans"
  search_key = "Name"
  search_value = "Silver"
  id_attribute = "Uuid"
  debug = true
}

I get this below error, when I terraform apply,

> $ terraform apply
data.restapi_object.acp_silver: Reading...
2022-08-08T18:53:57.119+0100 [ERROR] vertex "data.restapi_object.acp_silver" error: json: cannot unmarshal array into Go value of type map[string]interface 
{}
2022-08-08T18:53:57.120+0100 [ERROR] vertex "data.restapi_object.acp_silver" error: json: cannot unmarshal array into Go value of type map[string]interface 
{}
2022-08-08T18:53:57.121+0100 [ERROR] vertex "data.restapi_object.acp_silver (expand)" error: json: cannot unmarshal array into Go value of type map[string]interface {}
╷
│ Error: json: cannot unmarshal array into Go value of type map[string]interface {}
│
│   with data.restapi_object.acp_silver,
│   on account_plans.tf line 1, in data "restapi_object" "acp_silver":
│    1: data "restapi_object" "acp_silver" {

Can you please tell what in the API response is causing that error? And if there's a way to overcome?
Appreciate your help on this!

**Comment by jgrumboe** [comment]
Just my two cents:
Seems like your API is returning an array of objects instead of a single one under `/AccountPlans`.

**Comment by arun-a-nayagam** [comment]
Yes it does, as it's a search and not a GET, I am hoping passing an "id" attribute would help?

**Comment by arun-a-nayagam** [comment]
Closing as the search, results in an array.
