### ISSUE TITLE
[Question] How the methods are resolved?

### ISSUE THREAD

**Issue by EmmaWrong** [Mastercard/terraform-provider-restapi#191]
Hello,
I am trying to find out, how the update and delete method is resolved by the code.
For example: I create a new resource, everything is working. I want to update that resource. 
Currently only the create method is used by the resource. So when i change the create path to the update path and set PUT as create method, the resource is updated with the new value.
So the question is, how the code is aware of the update? How do I decide when to create and when to update?

`
```
resource "restapi_object" "create_cmmap" {
  count = local.cnfnotexists ? 1 : 0
  provider = ocprestapi.restapi_headers
  path = "/api/v1/namespaces/mynamespace/configmaps"
  id_attribute = "metadata/name"
  object_id    = "metadata/name"
  create_path = "/api/v1/namespaces/mynamespace/configmaps"
  update_path = "/api/v1/namespaces/mynamespace/configmaps/${var.CM_VALUE}"
 update_method = "PUT"
  data = "{\"kind\": \"ConfigMap\",\"apiVersion\": \"v1\",\"metadata\": {\"name\": \"${var.CM_NAME}\", \"namespace\": \"mynamespace\"},\"data\": {\"clustername\": \"cluster1\",\"environment\": \"${var.CM_VALUE}\"}}"
}
```
`

**Comment by jgrumboe** [comment]
Sorry, maybe it's obvious, but why don't you use the kubernetes configmap resource https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/config_map_v1 to manage a K8s configmap?

**Comment by EmmaWrong** [comment]
I think this has nothing to do with my question, and does not solve the problem. This was just a test what we can do with the provider. So I am not satisfied with this functionality and documentation and found another solution
