### ISSUE TITLE
Write to API where json body starts with [] not {}

### ISSUE THREAD

**Issue by garddolau** [Mastercard/terraform-provider-restapi#203]
Hi Team,

I'm trying to write to an API that requires the JSON data to start with [] and getting this error.
Is there any known workaround of this?

Error: data attribute is invalid JSON: json: cannot unmarshal array into Go value of type map[string]interface {}

Here is the API guide
https://learn.microsoft.com/en-us/rest/api/azure/devops/securityroles/roleassignments/set-role-assignments

resource "restapi_object" "environments_permissions" {
  provider = restapi.restapi_put
  path  = "my_api_path"
  data  = jsonencode([{
    "roleName" = "Administrator"
    "userId"   = "user_id"
  }])
}

Thanks,
Darren

**Comment by RedStalker** [comment]
Hello @garddolau,

Unfortunatelly I don't have an Azure account and I can't check it.
Have you tried to move [] out of json?
```tf
data = [jsonencode({
   "roleName" = "Administrator"
   "userId" = "user_id"
})]
```

Why don't you use [azurerm provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) that has azurerm_role_assignment resource?

**Comment by garddolau** [comment]
Found a workaround to now start json with []

**Comment by kellervater** [comment]
@garddolau 
What is your workaround. I happen to have the same problem.
I need to pass a nameless array. It works with using the http provider but not with restAPI because of the unmarshalling error.
