### ISSUE TITLE
PATCH sends entire body instead of what has changed

### ISSUE THREAD

**Issue by runultra** [Mastercard/terraform-provider-restapi#204]
After reading another similar issue, it was originally stated there is no way for this provider to understand what has changed and to only send the required fields for a PATCH. Just curious if this is still true, or if there is any changes in the future to allow this sort of behavior?

I have a data field that looks like this:
`data         = "{ \"name\": \"${var.name}\", \"subnet_cidr\": \"${var.subnet_cidr}\", \"domain_name\": \"${var.name}\", \"role\": \"${var.role}\", \"enabled\":${var.enabled} }"`

The var.role can only be sent when issuing method POST and not PATCH. Is there perhaps a way to have a conditional statement for specific fields based on what method is being used?

**Comment by DRuggeri** [comment]
Hi, @runultra - unfortunately, the situation still stands as initially described. There is no way for the provider to know which fields changed and only send the delta.

The general behavior is described in the README, but can be broken down like so:
* Create: Send the full object and expect an ID to come back
* Read: Issue a GET for the path+id
* Update: Send the full object to the path+id
* Delete: Send a DELETE to the path+id
