### ISSUE TITLE
Support For PUT Requests

### ISSUE THREAD

**Issue by ggsood** [Mastercard/terraform-provider-restapi#21]
Hi All

I am trying to use the restapi_object to fire a put request to my elastic search url, I am trying to create a new watcher as per api https://www.elastic.co/guide/en/elasticsearch/reference/current/watcher-api-put-watch.html

There is always a POST request getting sent, which is not supported as creating a new watcher only supports PUT request, i am not sure how can i import something from the apis as there is no id or parmater present.

below is my config
```
provider "restapi" {
  uri                  = "elastic.co"
  insecure = true
  write_returns_object = true
  debug                = true

  headers {
    Content-Type = "application/json"
  }
  username = "watcher"
  password = "watcher"
}

resource "restapi_object" "api" {
  path = "/_xpack/watcher/watch"
  object_id = "alert-1"
  update_path = "alert-1"
  data = "${data.template_file.alert.rendered}"
}
```

**Comment by DRuggeri** [comment]
I think this could be doable by adding a set of attributes like what was done for paths on each resource:
https://github.com/Mastercard/terraform-provider-restapi/blob/master/restapi/api_object.go#L15

I'd propose that this be set at the provider level rather than the resource level.

For your use cases, would it work if the CRUD operations were all the same?

**Comment by kmartin** [comment]
+1 I would also appreciate the ability to use PUT commands for create.

**Comment by meringu** [comment]
+1 I also have an API that only supports PUTs, and I'd need to override the paths to remove the `/{id}` from updates, gets, and deletions.

**Comment by DRuggeri** [comment]
@ggsood, @kmartin and @meringu - can you tell me if having `PUT` versus `POST` would be required at the individual resource level, or would it be OK to be set at the provider level? I ask because it'd make a lot of sense for this to be consistent behavior across anything the API you're talking to manages... but wanted to make sure.

**Comment by DRuggeri** [comment]
I don't have a way to test this... but I've created these methods at the provider level in the [variable_methods](https://github.com/Mastercard/terraform-provider-restapi/tree/variable_methods) branch.

Is it possible for any of you to build and test that it works as expected? For the configuration shared by @ggsood, it would now look like this:
```
provider "restapi" {
  uri                  = "elastic.co"
  insecure = true
  write_returns_object = true
  debug                = true

  headers {
    Content-Type = "application/json"
  }
  username = "watcher"
  password = "watcher"

  create_method = "PUT"
}

resource "restapi_object" "api" {
  path = "/_xpack/watcher/watch"
  object_id = "alert-1"
  update_path = "alert-1"
  data = "${data.template_file.alert.rendered}"
}
```

I'm curious if it also uses `PUT` for update activities or if you also have to change `update_method` to become something else (`POST` maybe).

If this works, I'll go ahead and merge this branch and push out `1.9.0` with the functionality.

**Comment by 2-face** [comment]
Currently I am using 1.8.0 version and in the resource I am setting:

  path = "<path>"
  update_path = "<path>"

However there is a POST request sent. I am not sure if I am misconfiguring sth or PUT is not supported.

**Comment by DRuggeri** [comment]
Awesome! Glad it's working out. I'll look to merge that branch in and provide a release soon (hopefully today!)

**Comment by DRuggeri** [comment]
Version `1.9.0` has been released to include this capability. Thanks!
