### ISSUE TITLE
internal validation failed; object ID is not set, but *may* have been created; this should never happen

### ISSUE THREAD

**Issue by karce25** [Mastercard/terraform-provider-restapi#220]
Hi 
I am working on creating tenants configuration on an F5 device through a JSON file,  the object is created but Terraform gives me the following error: 

internal validation failed; object ID is not set, but *may* have been created; this should never happen.

### **provider.tf**

provider "restapi" {
  uri      = "https://10.154.86.15:8888/"
  write_returns_object = true
  insecure = true
  create_returns_object = true
  debug = true
  headers = {
    Authorization  = var.token
    "Content-Type" = "application/yang-data+json"
  }

  create_method  = "POST"
  update_method  = "POST"
  destroy_method = "DELETE"
  
}

## **main.tf**

resource "restapi_object" "post_request" {
  data = "${file("tenant.json")}"
  path = "/restconf/data/f5-tenants:tenants"
 create_path = "/restconf/data/f5-tenants:tenants"  
}

Please let me know if there is an attribute that I missed

**Comment by RedStalker** [comment]
Hello @karce25 

The error 
```sh
internal validation failed; object ID is not set, but may have been created; this should never happen.
```
means that terraform didn't receive ID of the created resource. The API responce must have the following format:
```json
{
    ...
    "id": "...",
    ...
}
```
If responce from your api have different naming for ID you must specify it in the resource
```
id_attribute (String, Optional) Defaults to id_attribute set on the provider. 
Allows per-resource override of id_attribute (see id_attribute provider config documentation)
```
For exampe if ID is "object_id" the resource might look like:
```tf
resource "restapi_object" "post_request" {
    data = "${file("tenant.json")}"
    path = "/restconf/data/f5-tenants:tenants"
    create_path = "/restconf/data/f5-tenants:tenants"
    id_attribute = "object_id"
}
```
Please note that this ID will be used in next terraform launch and it will fail if it won't be able to read the created resource

**Comment by nwhobart** [comment]
What if the API returns something like this? 

```
{
  "data": {
    "private_apps": [
      {
        "app_id": 25,
        "app_name": "[blah_app]",
        "clientless_access": false,
        "host": "app.domain.com",
        "private_app_protocol": "http",
        "protocols": [
          {
          ....omitted for brevity....
```
          
According to the docs: 

>This value may also be a '/'-delimited path to the id attribute if it is multiple levels deep in the data (such as attributes/id in the case of an object { "attributes": { "id": 1234 }, "config": { "name": "foo", "something": "bar"}}


However my structure is different and setting this doesn't work (as i would expect):

```
  id_attribute = "data/private_apps/app_id"
```

**Comment by RedStalker** [comment]
Hi @nwhobart 
"private_apps" is a type of list[], and to access it you must use the list element in the path. So the id_attribute should look like
`id_attribute = "data/private_apps/0/app_id"`

**Comment by nwhobart** [comment]
@RedStalker 

Yeah actually I ended up being very stupid. That code I posted was from the API returning ALL the apps. When a specific app is called this gets returned: 

```

  "data": {
    "clientless_access": null,
    "host": "blah.host.com",
    "id": 133,
    "name": "[blah.app]",
    "private_app_protocol": null,
```

Which makes `id_attribute = "data/id"` simple enough. 

HOWEVER

When I try to plan/apply the first apply fails but if I immediately plan/apply right afterwards the apply is complete. 

The error I get is: 

```
╷
│ Error: unexpected response code '503': {"message":"name resolution failed"}
│
│   with module.blah_base_apps["blah"].restapi_object.private_apps,
│   on ../../../../modules/netskope/private_apps/main.tf line 51, in resource "restapi_object" "private_apps":
│   51: resource "restapi_object" "private_apps" {
│
╵
```

**Comment by RedStalker** [comment]
> @RedStalker
> 
> Yeah actually I ended up being very stupid. That code I posted was from the API returning ALL the apps. When a specific app is called this gets returned:
> 
> ```
> 
>   "data": {
>     "clientless_access": null,
>     "host": "blah.host.com",
>     "id": 133,
>     "name": "[blah.app]",
>     "private_app_protocol": null,
> ```
> 
> Which makes `id_attribute = "data/id"` simple enough.
> 
> HOWEVER
> 
> When I try to plan/apply the first apply fails but if I immediately plan/apply right afterwards the apply is complete.
> 
> The error I get is:
> 
> ```
> ╷
> │ Error: unexpected response code '503': {"message":"name resolution failed"}
> │
> │   with module.blah_base_apps["blah"].restapi_object.private_apps,
> │   on ../../../../modules/netskope/private_apps/main.tf line 51, in resource "restapi_object" "private_apps":
> │   51: resource "restapi_object" "private_apps" {
> │
> ╵
> ```
> 
> The module itself is super basic:
> 
> ```
> resource "restapi_object" "private_apps" {
>   data = jsonencode({
>     app_name   = var.app_name
>     host       = var.host
>     protocols  = var.protocols
>     publishers = local.filtered_data
>   })
> 
>   id_attribute = "data/id"
> 
>   path = "/api/v2/steering/apps/private"
> }
> ```

500 errors indicate server problems and should not be related to API requests. For debug purposes you can turn on debug and check the full HTTP responce from the server

`TF_LOG=debug terraform apply`

**Comment by nwhobart** [comment]
@RedStalker 

You're right about the `503` and my assumptions is this is a rate limiting issue: 

```
2023-07-14T11:12:33.385-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 api_client.go: BODY:: timestamp=2023-07-14T11:12:33.385-0700
2023-07-14T11:12:33.385-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 <none>: timestamp=2023-07-14T11:12:33.385-0700
2023-07-14T11:12:33.385-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 Waiting for rate limit availability: timestamp=2023-07-14T11:12:33.385-0700
2023-07-14T11:12:33.647-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 api_client.go: Response code: 503: timestamp=2023-07-14T11:12:33.647-0700
2023-07-14T11:12:33.647-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 api_client.go: Response headers:: timestamp=2023-07-14T11:12:33.647-0700
2023-07-14T11:12:33.647-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 api_client.go:   Ratelimit-Reset: 1: timestamp=2023-07-14T11:12:33.647-0700
2023-07-14T11:12:33.647-0700 [INFO]  provider.terraform-provider-restapi_v1.18.1: 2023/07/14 11:12:33 api_client.go:   X-Kong-Response-Latency: 118: timestamp=2023-07-14T11:12:33.647-0700
```

This server allows 4 requests per second and in the provider block i'm setting: 

```
  rate_limit           = 1
```  
so to me it seems like the provider is not respecting that?

**Comment by RedStalker** [comment]
@nwhobart 
Sorry.  Never used rate_limit with with provider and can't say anything here

**Comment by nwhobart** [comment]
Thanks for the help @RedStalker ... I'm passed my "major" issue and take the rest up with the API server.

**Comment by karce25** [comment]
> Hello @karce25
> 
> The error
> 
> ```shell
> internal validation failed; object ID is not set, but may have been created; this should never happen.
> ```
> 
> means that terraform didn't receive ID of the created resource. The API responce must have the following format:
> 
> ```json
> {
>     ...
>     "id": "...",
>     ...
> }
> ```
> 
> If responce from your api have different naming for ID you must specify it in the resource
> 
> ```
> id_attribute (String, Optional) Defaults to id_attribute set on the provider. 
> Allows per-resource override of id_attribute (see id_attribute provider config documentation)
> ```
> 
> For exampe if ID is "object_id" the resource might look like:
> 
> ```terraform
> resource "restapi_object" "post_request" {
>     data = "${file("tenant.json")}"
>     path = "/restconf/data/f5-tenants:tenants"
>     create_path = "/restconf/data/f5-tenants:tenants"
>     id_attribute = "object_id"
> }
> ```
> 
> Please note that this ID will be used in next terraform launch and it will fail if it won't be able to read the created resource

Thanks for the clarification :)
