### ISSUE TITLE
Several critical vulnerabilities due to stale dependencies & deactivated dependabot

### ISSUE THREAD

**Issue by danowensdev** [Mastercard/terraform-provider-restapi#224]
When checking this module from a security standpoint we found the following vulnerabilities due to stale dependencies:

|Dependency                                                          |Vulnerability IDs                                                               |Package                                                                        |Highest Severity|CVE Count|Confidence|EvidenceCount|
|--------------------------------------------------------------------|--------------------------------------------------------------------------------|-------------------------------------------------------------------------------|----------------|---------|----------|-------------|
|cloud.google.com/go/storage:1.10.0                                  |[`cpe:2.3:a:storage_project:storage:1.10.0:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Astorage_project&cpe_product=cpe%3A%2F%3Astorage_project%3Astorage&cpe_version=cpe%3A%2F%3Astorage_project%3Astorage%3A1.10.0)                          |pkg:golang/cloud.google.com/go/storage@1.10.0                                  |MEDIUM          |1        |High      |6            |
|github.com/armon/go-socks5:0.0.0-20160902184237-e75332964ef5        |[`cpe:2.3:a:socks5_project:socks5:0.0.0.20160902184237.e75332964.ef5:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Asocks5_project&cpe_product=cpe%3A%2F%3Asocks5_project%3Asocks5&cpe_version=cpe%3A%2F%3Asocks5_project%3Asocks5%3A0.0.0.20160902184237.e75332964.ef5)|pkg:golang/github.com/armon/go-socks5@0.0.0-20160902184237-e75332964ef5        |HIGH            |1        |High      |6            |
|github.com/gliderlabs/ssh:0.2.2                                     |[`cpe:2.3:a:ssh:ssh:0.2.2:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Assh&cpe_product=cpe%3A%2F%3Assh%3Assh&cpe_version=cpe%3A%2F%3Assh%3Assh%3A0.2.2)                                           |pkg:golang/github.com/gliderlabs/ssh@0.2.2                                     |HIGH            |3        |High      |6            |
|github.com/hashicorp/go-getter:1.6.2                                |[`cpe:2.3:a:hashicorp:go-getter:1.6.2:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ahashicorp&cpe_product=cpe%3A%2F%3Ahashicorp%3Ago-getter&cpe_version=cpe%3A%2F%3Ahashicorp%3Ago-getter%3A1.6.2)                               |pkg:golang/github.com/hashicorp/go-getter@1.6.2                                |MEDIUM          |1        |Highest   |6            |
|github.com/hashicorp/terraform-exec:0.13.0                          |[`cpe:2.3:a:hashicorp:terraform:0.13.0:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ahashicorp&cpe_product=cpe%3A%2F%3Ahashicorp%3Aterraform&cpe_version=cpe%3A%2F%3Ahashicorp%3Aterraform%3A0.13.0)                              |pkg:golang/github.com/hashicorp/terraform-exec@0.13.0                          |CRITICAL        |2        |Highest   |6            |
|github.com/hashicorp/terraform-plugin-go:0.2.1                      |[`cpe:2.3:a:hashicorp:terraform:0.2.1:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ahashicorp&cpe_product=cpe%3A%2F%3Ahashicorp%3Aterraform&cpe_version=cpe%3A%2F%3Ahashicorp%3Aterraform%3A0.2.1)                               |pkg:golang/github.com/hashicorp/terraform-plugin-go@0.2.1                      |CRITICAL        |3        |Highest   |6            |
|github.com/hashicorp/terraform-plugin-sdk/v2:2.4.3                  |[`cpe:2.3:a:hashicorp:terraform:2.4.3:*:*:*:*:*:*:*`]()                               |pkg:golang/github.com/hashicorp/terraform-plugin-sdk/v2@2.4.3                  |HIGH            |1        |Low       |6            |
|github.com/kevinburke/ssh_config:0.0.0-20190725054713-01f96b0aa0cd  |[`cpe:2.3:a:ssh:ssh:0.0.0.20190725054713.01.f96.b0:aa0:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Assh&cpe_product=cpe%3A%2F%3Assh%3Assh&cpe_version=cpe%3A%2F%3Assh%3Assh%3A0.0.0.20190725054713.01.f96.b0)                |pkg:golang/github.com/kevinburke/ssh_config@0.0.0-20190725054713-01f96b0aa0cd  |HIGH            |3        |High      |6            |
|github.com/keybase/go-crypto:0.0.0-20161004153544-93f5b35093ba      |[`cpe:2.3:a:keybase:keybase:0.0.0:*:*:*:*:*:*:*`]()                                   |pkg:golang/github.com/keybase/go-crypto@0.0.0-20161004153544-93f5b35093ba      |CRITICAL        |6        |Low       |6            |
|github.com/prometheus/client_model:0.0.0-20190812154241-14fe0d1b01d4|[`cpe:2.3:a:prometheus:prometheus:0.0.0:*:*:*:*:*:*:*`]()                             |pkg:golang/github.com/prometheus/client_model@0.0.0-20190812154241-14fe0d1b01d4|MEDIUM          |1        |Low       |6            |
|github.com/xanzy/ssh-agent:0.2.1                                    |[`cpe:2.3:a:ssh:ssh:0.2.1:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Assh&cpe_product=cpe%3A%2F%3Assh%3Assh&cpe_version=cpe%3A%2F%3Assh%3Assh%3A0.2.1)                                           |pkg:golang/github.com/xanzy/ssh-agent@0.2.1                                    |HIGH            |3        |High      |6            |
|google.golang.org/grpc:1.32.0                                       |[`cpe:2.3:a:grpc:grpc:1.32.0:*:*:*:*:*:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Agrpc&cpe_product=cpe%3A%2F%3Agrpc%3Agrpc&cpe_version=cpe%3A%2F%3Agrpc%3Agrpc%3A1.32.0)                                        |pkg:golang/google.golang.org/grpc@1.32.0                                       |MEDIUM          |1        |High      |3            |
|gopkg.in/yaml.v3:3.0.0-20200313102051-9f266ea9e77c                  |[`cpe:2.3:a:yaml_project:yaml:3.0.0:*:*:*:*:go:*:*`](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Ayaml_project&cpe_product=cpe%3A%2F%3Ayaml_project%3Ayaml&cpe_version=cpe%3A%2F%3Ayaml_project%3Ayaml%3A3.0.0)                                |pkg:golang/gopkg.in/yaml.v3@3.0.0-20200313102051-9f266ea9e77c                  |HIGH            |1        |Highest   |3            |

These vulnerabilities would be fixed by upgrading the dependencies, but the dependabot integration has also paused due to inactivity. Would it be possible to upgrade the dependencies to fix these vulnerabilities?

Note: The [Dependency-Check](https://jeremylong.github.io/DependencyCheck/general/thereport.html) tool was used to detect vulnerabilities.

**Comment by danowensdev** [comment]
Any updates @DRuggeri?

**Comment by DRuggeri** [comment]
Hi, @danowensdev - I just pushed a commit that updates all of the direct dependencies to the latest, but I notice that a number of the items reported are not actually used by the project. I haven't looked at the Dependency-Check tool to know how it works, but I think it is searching through go.sum for dependencies even if it's not used in go.mod.

**Comment by danowensdev** [comment]
Hi @DRuggeri, thanks for the fix! It seems the release didn't run through, could it be that the GPG key has expired? https://github.com/Mastercard/terraform-provider-restapi/actions/runs/5480151077/jobs/9982950166

**Comment by DRuggeri** [comment]
Yup - got the notification it failed and will give it a look. I may need to update some keys/etc

**Comment by DRuggeri** [comment]
All good now! You should see the releases

**Comment by danowensdev** [comment]
Many thanks, we will check again and ensure we do not pick up any false positives 👍
