### ISSUE TITLE
import is not documented

### ISSUE THREAD

**Issue by orgads** [Mastercard/terraform-provider-restapi#236]
It works, but I had to discover how to do it myself :)

**Comment by redzioch** [comment]
@orgads Any suggestion how to? :)

**Comment by orgads** [comment]
Sure :)

```
terraform import restapi_object.example /<full path from server root>/<object id>
```

**Comment by redzioch** [comment]
I saw that as an error when I tried to import anything. Problem is, that I do not provide ID in path, but in body.

**Comment by orgads** [comment]
Then no id. Just `/path`.

**Comment by orgads** [comment]
Propsed fix:
- #277
