### ISSUE TITLE
Allow to hide some data from logs output

### ISSUE THREAD

**Issue by ipleten** [Mastercard/terraform-provider-restapi#29]
It would be great to hide sensitive data from logs.
e.g
```
...
hide_data_path = 'json.user.password'
...
```
or hide "data" string  at all:
```data: <sensitive>```

**Comment by ipleten** [comment]
see #31

**Comment by DRuggeri** [comment]
Thank you so much for the PR. I've merged it!

**Comment by ipleten** [comment]
Thank you for merging! Could I ask you to release a new version (1.7.1 mb)?

**Comment by DRuggeri** [comment]
You bet. This is done (went with `1.8.0` since this is new functionality).
