### ISSUE TITLE
It would be helpful if allow arbitrary headers and content types

### ISSUE THREAD

**Issue by rberlind** [Mastercard/terraform-provider-restapi#3]
It would be helpful if arbitrary headers and could be added and other content types could be specified.

In particular, the authorization_header of the provider is too restrictive as currently implemented without the ability to add other headers. In particular, it hard-codes "Authorization: Bearer " in the header it creates. In the case of HashiCorp's Vault, one needs to add a header like "X-Vault-Token: f3b09679-3001-009d-2b80-9c306ab81aa6" and setting that as the value of authorization_header does not work since one ends up with "Authorization: Bearer X-Vault-Token: f3b09679-3001-009d-2b80-9c306ab81aa6" which does not work. 

With regard to the Terraform Enterprise API, the insertion of "Authorization: Bearer " is fine, but the hard-coded content type of "application/json" causes problems since the TFE API expects content-type of "application/vnd.api+json".  This is why being able to specify the content-type would be helpful.

**Comment by DRuggeri** [comment]
This is excellent feedback, @rberlind. With luck, I hope to have this added today.

**Comment by rberlind** [comment]
Awesome, @DRuggeri .  Thanks.

**Comment by rberlind** [comment]
I was able to get version 1.0 partially working with the Vault API, but had some issues as reported in https://github.com/Mastercard/terraform-provider-restapi/issues/5.  In particular, while the provider was able to create a Vault secret, it could not read the secret back.

It is possible that the Vault API does not fully adhere to REST protocols despite using JSON.

In any case, I can confirm that I can successfully pass headers needed by both Terraform and Vault APIs and am closing this issue.
