### ISSUE TITLE
upgrade to TF .12

### ISSUE THREAD

**Issue by on4tux** [Mastercard/terraform-provider-restapi#30]
according to https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers, .11 providers need to upgraded to work with TF .12

**Comment by DRuggeri** [comment]
Thanks for the heads up, @on4tux! The new release (`1.8.0`) has been bumped up to TF .12.

We've now also moved to a much less archaic form of vendoring packages and have started using `govendor` for managing vendored dependencies.
