### ISSUE TITLE
attribute of api_data not found until resource is created

### ISSUE THREAD

**Issue by iKrushYou** [Mastercard/terraform-provider-restapi#32]
I am creating a resource using 

```
resource "restapi_object" "server_name" {
  path = "/servernames/application"
  data = "{\"appcode\": \"${var.requestor_appcode}\",\"requestor\": \"${var.requestor_id}\"}"
}
```

and then accessing it via

```
name             = "${restapi_object.server_name.api_data.name}"
```

however, when running I get the error
```
* vsphere_virtual_machine.vm: Resource 'restapi_object.server_name' does not have attribute 'api_data.name' for variable 'restapi_object.server_name.api_data.name'
```

I was able to work around this by creating the restapi_object resource first (commenting out the vm resource) and applying and then uncommenting the rest and applying again. I've also tried adding a `depends_on = ["restapi_object.server_name"]` but that also doesn't seem to help.

Any ideas?

**Comment by iKrushYou** [comment]
Is this, perhaps, related to this issue? https://github.com/hashicorp/terraform/issues/17034

I'm hoping not because otherwise, this super super useful provider would no longer work for my use-case.

**Comment by iKrushYou** [comment]
@DRuggeri sorry to call you out directly but I see you're quite active on this repo. Have you happened to have used this provider in such a use case where the value from a resource is used in another resource? To me, it seems like a pretty simple use-case but I can't get it to work no matter what I try. I'm currently waiting on someone I'm working with from Hashi to get back to me about this issue to see if it's something on their end (directly related to the previous issue I shared)

Best,
Alex

**Comment by DRuggeri** [comment]
No worries, @iKrushYou. I haven't tested the behavior you describe, but it does sound feasible that the bug you're seeing is related to the one you linked. Have you tried setting something up with `fakeserver` so you could observe the order which things are executed between the provider and the server?

**Comment by iKrushYou** [comment]
@DRuggeri so far I've been running off of my own API server that I already had set up. I can attempt to replicate the issue using the fakeserver so that you can have the same environment on your own computer

**Comment by iKrushYou** [comment]
Using the fakeserver, I've recreated the situation.

```
provider "restapi" {
  uri                  = "http://localhost:9000/api"
  insecure             = true
  write_returns_object = true
}

resource "restapi_object" "testobject1" {
  path = "/objects"
  data = "{\"id\": 4, \"name\": \"testobject1\"}"
}

resource "restapi_object" "testobject2" {
  path = "/objects"
  data = "{\"id\": 5, \"name\": \"${restapi_object.testobject1.api_data.name}\"}"
}
```

If `testobject1` is created before `testobject2` is added to the tf file, then there are no issues. However, if an `apply` is run when the resource in `testobject1` is not created yet, then we get the same error:

```
Error: Error running plan: 1 error(s) occurred:

* restapi_object.testobject2: 1 error(s) occurred:

* restapi_object.testobject2: Resource 'restapi_object.testobject1' does not have attribute 'api_data.name' for variable 'restapi_object.testobject1.api_data.name'
```

**Comment by spartakb** [comment]
@iKrushYou after a much struggle personally with a similar issue, I think I have a workaround.

Instead of accessing the object directly via `${restapi_object.testobject1.api_data.name}` try to access them using the lookup() function.   ex:  `${lookup(restapi_object.testobject1.api_data,"name")}`

Since `api_data` is part of the hardcoded declaration by the provider, then TF accepts it as a map type.

Try this version of your example from above:
```
provider "restapi" {
  uri                  = "http://localhost:9000/api"
  insecure             = true
  write_returns_object = true
}

resource "restapi_object" "testobject1" {
  path = "/objects"
  data = "{\"id\": 4, \"name\": \"testobject1\"}"
}

resource "restapi_object" "testobject2" {
  path = "/objects"
  data = "{\"id\": 5, \"name\": \"${lookup(restapi_object.testobject1.api_data,"name")}\"}"
}
```

**Comment by DRuggeri** [comment]
This is awesome, @spartakb! Any way I could convince you to open a PR with this example running against `fakeserver` with some comments in the .tf file explaining why it's needed?

**Comment by DRuggeri** [comment]
Closing old issue - workaround is available, but a test case is still welcome 😄
