### ISSUE TITLE
Create Method Being Set to Put

### ISSUE THREAD

**Issue by HammerTime86** [Mastercard/terraform-provider-restapi#39]
If the "update_method" option is not set, why is the "create_method" being set to a PUT? 
 See [api_client, line 87](https://github.com/Mastercard/terraform-provider-restapi/blob/c27f9f8d224e2791b875a3725208a6aeec3a573a/restapi/api_client.go#L87).  Shouldn't the "update_method" be defaulted to PUT instead?

**Comment by DRuggeri** [comment]
Yes - terrible error on my part! This was fixed in #42 by @kody-abe and just released as `v1.9.1`.
