### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by kody-abe** [Mastercard/terraform-provider-restapi#41]
Trying to use the provider but get

* module.test_nodeping.provider.restapi: fork/exec /Users/kody/.terraform.d/plugins/darwin_amd64/terraform-provider-restapi_v1.9.0: exec format error

Tried versions 1.7.0-1.9.0 - I am using terraform 0.11

**Comment by enummela** [comment]
@kody-abe did you manage to get this provider working? I'm running into this error as well. Same arch and os.

**Comment by kody-abe** [comment]
@enummella yes I got it working. I was curling the release but not following redirects. So the release package I downloaded was HTML. So, be sure to very the contents of the package by opening in a text editor.

**Comment by enummela** [comment]
@kody-abe your solution also fixed the issue I was having. Cheers!

If anyone else comes across this issue, use the `-L` flag to make cURL follow redirects.

```
curl -LO https://github.com/Mastercard/terraform-provider-restapi/releases/download/v1.9.2/terraform-provider-restapi_v1.9.2-darwin-amd64
```
