### ISSUE TITLE
Object creation/deletion it not working properly

### ISSUE THREAD

**Issue by k4ch0** [Mastercard/terraform-provider-restapi#43]
Hi,

I'm using this provider to interact with the [Rackspace Load Balancers API](https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/load-balancers/).
So far it is working to create a new LB's, but it is not deleting the one that was already created, only creates new LBs instead of deleting the one that was already created an create a new one.

I'm using this code:

nodes_json => Using this to generate a template with the nodes that I will attach to the LB.
data_json => Using this to put all my variables together
token => Generates my auth-token
create_lb => API call to create the LB, and I assume to delete it but seems like it is not working.

```
provider "restapi" {
  uri     = "https://iad.loadbalancers.api.rackspacecloud.com/v1.0/${var.openstack_tenant_name}/loadbalancers"
  debug   = true
  write_returns_object = true
  create_returns_object = true
  create_method = "POST"
  update_method = "POST"
  headers = {
    Content-Type = "application/json",
    X-Auth-Token = data.external.token.result["token"]
  }
}

data "template_file" "nodes_json" {
  template = "${file("${path.module}/templates/nodes_lb.json.tmpl")}"
  count       = "${var.openstack_count}"
  vars = {
    node_address = "${element(openstack_compute_instance_v2.nodes.*.network.1.fixed_ip_v4, count.index)}"
  }
}

data "template_file" "data_json" {
  template = "${file("${path.module}/templates/create_lb.json.tmpl")}"
  vars = {
    lb_name = "${var.openstack_lb_name}"
    lb_port = "${var.openstack_lb_exposed_port}"
    lb_protocol = "${var.openstack_lb_protocol}"
    lb_timeout = "${var.openstack_lb_timeout}"
    lb_algorithm = "${var.openstack_lb_algorithm}"
    lb_nodes = "${join(",", data.template_file.nodes_json.*.rendered)}"
  }
}

data "external" "token" {
  program = [
    "files/get_token.sh",
    "-e",
    "${var.openstack_auth_url}/tokens",
    "-u",
    "${var.openstack_username}",
    "-a",
    "${var.openstack_apikey}",
  ]
}
resource "restapi_object" "create_lb" {
  path = "/"
  create_path = "{id}"
  read_path = "{id}"
  update_path = "{id}"
  destroy_path = "{id}"
  id_attribute = "loadBalancer/id"
  debug = true
  data = "${data.template_file.data_json.rendered}"
}
```

create_lb.json.tmpl
```
{ 
  "loadBalancer": 
  { 
    "name"       : "${lb_name}",
    "port"       : "${lb_port}",
    "protocol"   : "${lb_protocol}",
    "timeout"    : "${lb_timeout}",
    "algorithm"  : "${lb_algorithm}",
    "virtualIps" : [ 
      { 
        "type": "PUBLIC" 
      } 
    ],
    "nodes"      : [
      ${lb_nodes}
    ] 
  }
}
```

get_token.sh
```
#!/bin/bash

#set -eux

function usage() {
  # NOTE: Keep sorted for easy git merges
  cat << E_O_F
Usage:
  -e Endpoint
  -u username
  -a API Key
E_O_F
}

function check_deps() {
  test -f $(which jq) || error_exit "jq command not detected in path, please install it"
}

# NOTE: Keep sorted for easy git merges
while getopts "a:e:u:h?" opt; do
    case "$opt" in
    e) ENDPOINT=${OPTARG}
    ;;
    u) USERNAME=${OPTARG}
    ;;
    a) API_KEY=${OPTARG}
    ;;
    h|\?)
        usage
        exit 0
        ;;
    esac
done

check_deps
TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{ "auth": { "RAX-KSKEY:apiKeyCredentials": { "username": "'$USERNAME'", "apiKey": "'$API_KEY'" } } }' $ENDPOINT | jq '.access.token.id' | tr -d "\"")
jq -n --arg token "$TOKEN" '{"token":$token}'
```

Any light is helpful.

**Comment by DRuggeri** [comment]
Hi, @k4ch0. I may not understand the use case. What are you changing that you expect objects to be deleted and new ones created? Are you meaning that changes to the .tf file are not modifying the existing loadbalancers defined in your state file?

**Comment by k4ch0** [comment]
Hello @DRuggeri, thank you for answering.

The first time when I run `terraform apply` the provider creates an LB, as expected, but the consequents runs I expect to read the Terraform state and DO NOT create a new LB, instead of that it creates a new LB everytime.
I run several times a `terraform apply` command to add more resources to my infrastructure, but I'm not modifying the LB, the LB should be the same one once is created.

Also, when I run `terraform destroy`, the LB is not destroyed.

Let me know if I explain myself.

**Comment by DRuggeri** [comment]
Thanks, I think that does help. Unfortunately, the indirection through the template is making it difficult for me to tell what's happening. You do see the LB in the state file, right?

It might help to enable debug as documented in `README.md` to see if that sheds some light? Each `api_object` that gets created will get logged (even if created from state), so that could help identify what Terraform is expecting to see and then what it does with that information. Based on the description, I would assume the `id` being wrong somehow is the culprit since that is the only thing that should govern the creation/deletion of entire objects.

**Comment by DRuggeri** [comment]
Closing this issue for the time being since it's been a while. Feel free to reopen and add additional info.
