### ISSUE TITLE
Reuse API call with different data (templates)

### ISSUE THREAD

**Issue by k4ch0** [Mastercard/terraform-provider-restapi#44]
Hi,

On issue #43 I mentioned that I'm creating some LB's with an API calls, and I generate a template with some data, and to create a new LB I just need to update a few parameters of my template.
Instead of having template1, template2,..., templateN, and restapi_object1, restapi_object2, etc there is a process to reuse the same API call using diferent data/template each time??

Thanks in advance

**Comment by DRuggeri** [comment]
Hi, @k4ch0. There's nothing in this provider to facilitate that, but perhaps a novel use of built-in functions can help?

Something like... https://stackoverflow.com/a/46838756?

**Comment by DRuggeri** [comment]
If possible, or you find a useful solution, please do share it here. For now I'll close the issue as something that we cannot support.
