### ISSUE TITLE
ID Incorrectly Expressed In Scientific "E" Notation

### ISSUE THREAD

**Issue by enummela** [Mastercard/terraform-provider-restapi#51]
The ID attribute of my API object is being expressed in scientific "E" notation instead of decimal notation.

Here is the output from my Terraform state.

```
resource "restapi_object" "check" {
    api_data    = {
        "check" = "map[id:5.3502e+06 name:mydomain.com]"
    }
    create_path = "/checks?encryption=true&host=mydomain.com&name=mydomain.com&notifyagainevery=0&paused=false&port=443&resolution=1&sendnotificationwhendown=3&teamids=&type=http&url=%2Fhealth_check.php&userids="
    id          = "5.3502e+06"
    path        = "/checks"
    update_path = "/checks{id}?encryption=true&host=mydomain.com&name=mydomain.com&notifyagainevery=0&paused=false&port=443&resolution=1&sendnotificationwhendown=3&teamids=&type=http&url=%2Fhealth_check.php&userids="
}
```

Comparing the Terraform state with the actual response suggests the notation problem is originating from within the provider and not the REST API.

```
{
    "check": {
        "id": 5350200,
        "name": "mydomain.com"
    }
}
```

Since the ID is expressed as `5.3502e+06` instead of `5350200` the `terraform destroy` operation is failing to refresh the object's state using the API as the Terraform debug log shows.

```
2019-07-23T12:17:03.717-0700 [DEBUG] plugin.terraform-provider-restapi_v1.9.2: 2019/07/23 12:17:03 api_client.go: method='GET', path='/checks/5.3502e+06', full uri (derived)='https://api.pingdom.com/api/2.1/checks/5.3502e+06', data=''
2019-07-23T12:17:03.717-0700 [DEBUG] plugin.terraform-provider-restapi_v1.9.2: 2019/07/23 12:17:03 api_client.go: Sending HTTP request to https://api.pingdom.com/api/2.1/checks/5.3502e+06...
...
Error: Unexpected response code '403': {"error":{"statuscode":403,"statusdesc":"Forbidden","errormessage":"Invalid check identifier"}}
```

FWIW I believe I configured the provider to properly extract the ID using the argument `id_attribute = "check/id"`.

**Comment by DRuggeri** [comment]
Hi, @enummela. Thanks for the report! This looks like something that escaped the test cases. Apparently beyond 8-ish bytes or so, golang will switch to scientific notation when converting a float64 to string.

I've made a few commits and pushed a new release (`v1.9.3`) that should address this. Would you mind testing and letting me know how it works out?

**Comment by enummela** [comment]
Hi @DRuggeri, based on my test, release v1.9.3 has fixed the issue. Appreciate the quick fix! Cheers!
