### ISSUE TITLE
Feature Request: Patch support

### ISSUE THREAD

**Issue by delaman** [Mastercard/terraform-provider-restapi#53]
Please support the PATCH verb.

**Comment by DRuggeri** [comment]
The method is used as a plain old string from inputs:
https://github.com/Mastercard/terraform-provider-restapi/blob/master/restapi/api_client.go#L167

Have you tried setting `update_method` to `PATCH` and experienced an error? This should work already.

**Comment by DRuggeri** [comment]
Closing this issue since it's been a while. Feel free to reopen with more information if the test doesn't work out.
