### ISSUE TITLE
Referencing nested IDs

### ISSUE THREAD

**Issue by Japeth** [Mastercard/terraform-provider-restapi#55]
Just need a little help wrapping my head around this:
but say I have an API with nested IDs, how would I reference this in terraform?
For example, a URL of a customer object is https://api.website.com/v1/customers
and the customer object has multiple nested objects that have ID fields. For example https://api.website.com/v1/customers/<customer_id>/products/<product_id>
I need to create/set products that are attached to a customer using TF.

I'm still a bit new to TF.

**Comment by DRuggeri** [comment]
Hi, Japeth. Not too difficult of a setup. What you would need to do is create a `datasource` object to find the customer that exists (unless you're creating it with this provider). There are search parameters to set/etc.

Once you have the datasource, presumably the ID is available as an attribute coming back from the `datasource` so you could create a `resource` like so:
```
data "restapi_object" "Customer" {
  path = "/v1/customers"
  search_key = "customer_name"
  search_value = "FooCorp"
}

resource "restapi_object" "Foo" {
  path = "/v1/customers/${data.restapi_object.Customer.api_data.id}"
  data = "{ \"id\": \"1234\", \"first\": \"Foo\", \"last\": \"Bar\" }"
}
```

This is lightly covered in the examples, but if you have a more specific example that would be useful, feel free to open a pull request!

**Comment by Japeth** [comment]
Thanks @DRuggeri 
I think I understand now.
