### ISSUE TITLE
RestAPI Provider

### ISSUE THREAD

**Issue by wb529kq** [Mastercard/terraform-provider-restapi#56]
Where/how do I download the binaries for this does not work directly with Terraform v0.12.6 ?

The installation guide talks about downloading Binaries ?

**Comment by DRuggeri** [comment]
Apologies for the slow response. The binaries are available on the releases page here on GitHub. I *believe* these support 0.12.6. Have you tried them?

**Comment by DRuggeri** [comment]
Closing this issue since it's been a while and it seems the information has been provided. Please feel free to reopen if needed.
