### ISSUE TITLE
Access REST Endpoint thru Proxy

### ISSUE THREAD

**Issue by vrvenky1407** [Mastercard/terraform-provider-restapi#62]
Hi

   I am trying to access a REST API Endpoint from my internal network thru Proxy.  It is giving the below error 

1 error(s) occurred:

* restapi_object.create-request: 1 error(s) occurred:

* restapi_object.create-request: Put https://console-d.dynecon.com/NetworkAutomation/rest/v1/ChangeRequest: dial tcp 34.96.75.80:443: connect: connection timed out

When I submit a Curl request from the same server, it is working fine.  So the proxy is working fine,  it is only when I try to connect using Mastercard Provider it is not able to utilize the Proxy setting defined in the Environment.  

How to utilize the http_proxy and https_proxy in this Mastercard Provider.

**Comment by DRuggeri** [comment]
I think it's as simple as using the correct environment variable. It looks like Go uses `HTTP_PROXY` and `HTTPS_PROXY` rather than the lower case variant that others use.

Please try that out and feel free to reopen the issue if you're still seeing a problem

**Comment by vrvenky1407** [comment]
Hi 

  I set the  Env variables to Uppercase and ran the terraform script but still getting the same issue.

# env | grep PROXY
HTTPS_PROXY=http://10.8.225.113:3128
HTTP_PROXY=http://10.8.225.113:3128

# terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + restapi_object.create-request
      id:         <computed>
      api_data.%: <computed>
      data:       "{\"Description\": \"Venkat request from TF RestAPI\",\"AdditionalInformation\": \"Testing create req Terraform RestAPI\", \"ApplicationProfileId\": 35, \"Requestor\": \"Venkatraman Ramakrishnan\"}\n"
      path:       "/NetworkAutomation/rest/v1/ChangeRequest"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

restapi_object.create-request: Creating...
  api_data.%: "" => "<computed>"
  data:       "" => "{\"Description\": \"Venkat request from TF RestAPI\",\"AdditionalInformation\": \"Testing create req Terraform RestAPI\", \"ApplicationProfileId\": 35, \"Requestor\": \"Venkatraman Ramakrishnan\"}\n"
  path:       "" => "/NetworkAutomation/rest/v1/ChangeRequest"
restapi_object.create-request: Still creating... (10s elapsed)
restapi_object.create-request: Still creating... (20s elapsed)
restapi_object.create-request: Still creating... (30s elapsed)
restapi_object.create-request: Still creating... (40s elapsed)
restapi_object.create-request: Still creating... (50s elapsed)
restapi_object.create-request: Still creating... (1m0s elapsed)
restapi_object.create-request: Still creating... (1m10s elapsed)
restapi_object.create-request: Still creating... (1m20s elapsed)
restapi_object.create-request: Still creating... (1m30s elapsed)
restapi_object.create-request: Still creating... (1m40s elapsed)
restapi_object.create-request: Still creating... (1m50s elapsed)
restapi_object.create-request: Still creating... (2m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* restapi_object.create-request: 1 error(s) occurred:

* restapi_object.create-request: Put https://console-d.dynecon.com/NetworkAutomation/rest/v1/ChangeRequest: dial tcp 34.96.75.80:443: connect: connection timed out

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Please let me know if I am doing anything wrong.  I am able to get the CURL request work in terraform script.

Thanks
