### ISSUE TITLE
Doesn't work inside alpine based docker image

### ISSUE THREAD

**Issue by duanshiqiang** [Mastercard/terraform-provider-restapi#65]
This plugin doesn't work with alpine based terrraform docker image (which the official terraform docker image is the case).

When trying to use the plugin, it will give errors like below:

```
Error: Failed to instantiate provider "restapi" to obtain schema: fork/exec /workspace/terraform.d/plugins/linux_amd64/terraform-provider-restapi_v1.9.3: no such file or directory
```

After some google search, it seems to be a known issue with CGO and Alpine Linux.  When doing `go build`,  `CGO_ENABLED=0` needs to be set.

**Comment by DRuggeri** [comment]
Sorry for the delay. I've been traveling.

This looks good - thanks for the PR! I'll fold it into a release very soon.
