### ISSUE TITLE
Ignore read response

### ISSUE THREAD

**Issue by gouraharidas** [Mastercard/terraform-provider-restapi#68]
I am doing a PUT/POST on an api which does not return anything in response body. In that case terraform always throw the following error since the response body is empty.

I am using terraform-provider-restapi to place a PUT/POST call to slack. Here is my provider config.

`provider "restapi" {
  update_method = "PUT"
  id_attribute = "username"
  write_returns_object = false
  uri = "https://hooks.slack.com/services"
  headers = {
    "Accept" = "text/plain"
    "Content-Type" = "application/json"
  }
}`

Since slack rest call doesn't return anything, and **terraform-provider-restapi** is trying to read the response, which ends up throwing the following error.

`unexpected end of JSON input`

Is there any option available?

**Comment by DRuggeri** [comment]
Hi, @gouraharidas. I'm afraid not. This Terraform resource is used to manage a stateful object on the server side based on a few standard REST semantics. It doesn't seem like this resource is the appropriate tool to make this call to Slack.
