### ISSUE TITLE
default provider needed if using aliases

### ISSUE THREAD

**Issue by ptone** [Mastercard/terraform-provider-restapi#69]
This is mostly for x-ref in case someone runs into this when using this provider.

If you are using multiple providers using Terraform's feature to alias providers, you will get an error on destroys

```
Error: Missing required argument

The argument "uri" is required, but was not set.
```

This is from https://github.com/hashicorp/terraform/issues/21330

A workaround is to include a dummy default:

```
provider "restapi" {
  # Default provider for rest API to avoid error on destroy WRT uri argument
  # https://github.com/hashicorp/terraform/issues/21330
  uri                  = "dummy"
}
```

**Comment by DRuggeri** [comment]
Cool - thanks for providing a pointer, @ptone! I'll close this issue, but do feel free to reopen if there's additional info needed.
