### ISSUE TITLE
Unable to find provider binary

### ISSUE THREAD

**Issue by jmeldrum76** [Mastercard/terraform-provider-restapi#70]
Hi,

Thanks for creating this.  I would use this provider however after cloning the repo, I can't seem to identify the binaries or create then with a "make build"

Any help would be greatly appreciated.

**Comment by DRuggeri** [comment]
Hi, @jmeldrum76. I would encourage just using the binaries published in the [releases](https://github.com/Mastercard/terraform-provider-restapi/releases).

If you'd like to build, on Linux you can run the build.sh script after installing go and govendor. Hope that helps - feel free to reopen the issue if you need more info!

**Comment by jmeldrum76** [comment]
Daniel,

 

Perfect, I will do some testing today.

 

Thanks,

 

Jeremy Meldrum

**Comment by jmeldrum76** [comment]
Hi, 

I was able to get the plugin installed.  Now when I run " terraform apply" This is what I get:

### **Terraform File:**

`provider "restapi" {
  uri                  = "https://venafiserver.se.venafi.com:443/"
  insecure = true
  debug                = true
  write_returns_object = true
}

resource "restapi_object" "Authorize" {
  path = "/vedsdk/authorize"
  #data = "{ \"id\": \"1234\", \"first\": \"Foo\", \"last\": \"Bar\" }"
  data = "{ \"Username\": \"administrator\", \"Password\": \"MyPassw0rd\"}"
}`

### **Output from Console**
`
venafilab@ubuntu:~/terraform/REST_API_Test$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # restapi_object.Authorize will be created
  + resource "restapi_object" "Authorize" {
      + api_data        = (known after apply)
      + api_response    = (known after apply)
      + create_response = (known after apply)
      + data            = jsonencode(
            {
              + Password = "MyPassword"
              + Username = "administrator"
            }
        )
      + id              = (known after apply)
      + path            = "/vedsdk/authorize"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

restapi_object.Authorize: Creating...

**Error: Internal validation failed. Object ID is not set, but *may* have been created. This should never happen!**

  **on cert_request_and_API.tf line 9, in resource "restapi_object" "Authorize":
   9: resource "restapi_object" "Authorize" {**
`

**Comment by DRuggeri** [comment]
Hi, @jmeldrum76 
Since terraform is used to manage resources, and the portion you've put up here is not a resource (it's a login "action"), the lifecycle activities that terraform needs (thus, this provider) are not applicable. It's hard to describe, but this provider is intended to manage objects. Your login action will need to be done elsewhere, but fed into this provider (by setting the HTTP headers).
