### ISSUE TITLE
Add a way to import resources

### ISSUE THREAD

**Issue by rolandg** [Mastercard/terraform-provider-restapi#72]
It would be great to have a way to import existing api resources to the terraform state.

**Comment by DRuggeri** [comment]
Hi there, @rolandg. Thanks for pinging about this. The ability to import resources has always been supported, but the documentation didn't mention it in the least bit! I've fixed that in 05941cd82e03b95493e2e26c7c850b6a0a27af21. Please give the updates a look and feel free to reopen the issue if it's not clear enough.

**Comment by rolandg** [comment]
Not sure if the documentation is correct. When I try with just the ip I get
```
[I] ➜ terraform import restapi_object.http_checks\[\"ts.example.com\"\] 440542                            
restapi_object.http_checks["ts.example.com"]: Importing from ID "440542"...

Error: Invalid path to import api_object '440542'. Must be /<full path from server root>/<object id>
...
```
With the full path it shows
```
[I] ➜ terraform import restapi_object.http_checks\[\"ts-premium.onlim.com\"\] /api/v1/checks/440542/
restapi_object.http_checks["ts-premium.onlim.com"]: Importing from ID "/api/v1/checks/440542/"...

Error: Cannot read an object unless the ID has been set.
...
```
Just curious regarding the first message. I think the problem here is that the api requires the slash at the end. I'll open another bug report for that case.

**Comment by DRuggeri** [comment]
You're right - I had an error in the syntax! I've fixed this in the readme and example .tf file. Thanks for the pointer

I'll take a look at the proposed PR and continue the conversation there
