### ISSUE TITLE
Support importing for apis that require trailing slashes after the id

### ISSUE THREAD

**Issue by rolandg** [Mastercard/terraform-provider-restapi#73]
I try to import api objects from the uptime.com api (https://uptime.com/api/v1/docs/) which requires a slash after the id in the url. 

https://github.com/Mastercard/terraform-provider-restapi/blob/351c5f45ad6189aeef7cc475f669efa0fba49103/restapi/resource_api_object.go#L108

maybe something like this could work:
```go
if (strings.LastIndex(input, "/") == len(input))
  n := strings.LastIndex(input, "/")
else
  n := strings.LastIndex(input[0,-1], "/")
```
will try that out when i have some spare time

**Comment by DRuggeri** [comment]
All set and released in `v1.11.0`
