### ISSUE TITLE
initialize resource only once

### ISSUE THREAD

**Issue by rolandg** [Mastercard/terraform-provider-restapi#75]
I have the use-case that I need to initialize a certain api resource only once when I create the cluster.
After the resource is created it exists for a while and gets rolled over at some point.

After the rollover I get the following error:
```
Error: Unexpected response code '404': {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [logs-000001]","resource.type":"index_or_alias","resource.id":"logs-000001","index_uuid":"_na_","index":"logs-000001"}],"type":"index_not_found_exception","reason":"no such index [logs-000001]","resource.type":"index_or_alias","resource.id":"logs-000001","index_uuid":"_na_","index":"logs-000001"},"status":404}
```
what I tried:
```hcl
  # only create this once
  lifecycle {
    ignore_changes = all
  }
```

Could this be solved at the provider level with something like `init_resource = true` and ignore all 404 to that resource after creation?
Alternativeliy I'd make a bash script with local-exec that ignores the 404.

**Comment by DRuggeri** [comment]
Hi, @rolandg. I'm afraid this provider isn't a good fit for that kind of use-case since it expects the created resource to remain at a stable location for ongoing management of the object.

If you do come across a working pattern (even if it's unrelated to this provider), please do share it in response to this issue in case others come across it.

**Comment by rolandg** [comment]
what i use for now:
```hcl
resource "shell_script" "bootstrap-index-logs" {
  environment = {
    DATA = var.data
    CLUSTER_NAME = var.cluster.name
  }

  depends_on = [restapi_object.req]

  lifecycle_commands {
    read = <<SCRIPT
      echo '{"done": "true"}' >&3
    SCRIPT

    create = <<SCRIPT
      curl -X PUT -H "Content-Type: application/json" -d "$DATA" "https://elasticsearch.example.com/logs-$CLUSTER_NAME-000001"
    SCRIPT

    update = <<SCRIPT
      echo "no diff no update ;)"
    SCRIPT

    delete = <<SCRIPT
      echo "cannot destroy init resource"
    SCRIPT
  }
}

```
