### ISSUE TITLE
Does restapi provider handle tfstate drift from real world infrastructure ? 

### ISSUE THREAD

**Issue by NamrathaG** [Mastercard/terraform-provider-restapi#77]
I deployed a resource using restapi provider, but the resource was deleted manually by mistake. 

On running `terraform plan`, I get the following error : 
`Error: Unexpected response code '404': { "errorcode": 10011, "message": "Resource does not exist", "severity": "ERROR" }` 

What I expect on `terraform plan` : Terraform does a refresh, learns that the resource does not exist, plans for the resource to be recreated. 

What I expect on `terraform apply` : Restapi provider does a POST request and the resource is recreated.

**Comment by NamrathaG** [comment]
For example if an azure resource group was deleted by mistake using azure portal, azure terraform provider handles it by deleting the state from tfstate and plans for it's re-creation.
`2020-02-20T15:24:59.589+0530 [DEBUG] plugin.terraform-provider-azurerm_v1.44.0_x4: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'tfvmexsdf-resources' could not be found."}}
2020-02-20T15:24:59.589+0530 [INFO]  plugin.terraform-provider-azurerm_v1.44.0_x4: [INFO] Error reading resource group "/subscriptions/722985c7-a1b4-4761-957f-39cd8869a2de/resourceGroups/tfvmexsdf-resources" - **removing from state**` 

Can restapi provider handle this case ?

**Comment by DRuggeri** [comment]
Hi, @NamrathaG 
I'll have to be honest... I didn't think that was an option! It looks like the azurerm provider just unsets the ID and returns nil on read. I've done this in the provider and will release an updated version.

**Comment by jamesdavidson** [comment]
To give an updated answer to the original question: yes, recreate on missing works in v2.0.1 of this provider.
