### ISSUE TITLE
Datasource from API which returns object (not array)

### ISSUE THREAD

**Issue by hongkongkiwi** [Mastercard/terraform-provider-restapi#92]
Hi there, 

I'm using a system health endpoint, this endpoint returns a single object instead of an array.

I want to setup a datasource to pull information from the system health endpoint.

Here's a simple example:
```
{
  "systemConfiguration": {
    "auditLogConfiguration": {
      "delete": {
        "enabled": false,
        "numberOfDaysToRetain": 365
      }
    }
  }
}
```

How can I get this object as a datasource using this plugin? It seems it only supports returning arrays (?)

**Comment by DRuggeri** [comment]
Hi, @hongkongkiwi 
You're correct, this data source was created to work with lists of data coming back from an API. If you do not need to filter through the results, does the built-in Terraform `external` resource fit the bill?

**Comment by DRuggeri** [comment]
It's been a while since this issue has had any activity so I'm going to close it for now. Please feel free to reply if you have more info to share.
