### ISSUE TITLE
How to set object ID correctly based on response ?

### ISSUE THREAD

**Issue by irom77** [Mastercard/terraform-provider-restapi#97]
Posting forward zone to Infoblox correctly but getting this Error: Internal validation failed. Object ID is not set. 
```
resource "restapi_object" "Demo_fwd" {
  path = "/zone_forward"
  data = "{\"fqdn\":\"testapi139.me360.com\",\"forward_to\":[{\"address\":\"10.10.10.10\", \"name\":\"testapi.shared360dev.com\"}]}"
  id_attribute = "_ref"
}
```
When doing the same from Postman I am getting response like below, so not sure how to setup id_attribute in the resource above

`"zone_forward/ZG5zLnpvbmUkLl9kZWZhdWx0LmNvbS5hZHZpc29yMzYwLnRlc3RhcGkyMDE:testapi139.me360.com/Internal"`

**Comment by TryTryAgain** [comment]
@irom77 ...what was your solution?

**Comment by irom77** [comment]
Described it [here](https://medium.com/@IrekRomaniuk/terraform-rest-api-provider-425d92efb9b) , basically making infoblox return object (?_return_as_object=1)

**Comment by dferns11** [comment]
hi @irom77 the page is not available but don't suppose you can share your solution?
